In [1]:
!pip install huggingface
!pip install huggingface_hub
!pip install transformers

Collecting huggingface
  Downloading huggingface-0.0.1-py3-none-any.whl.metadata (2.9 kB)
Downloading huggingface-0.0.1-py3-none-any.whl (2.5 kB)
Installing collected packages: huggingface
Successfully installed huggingface-0.0.1
Requirement already satisfied: huggingface_hub in /usr/local/lib/python3.12/dist-packages (1.4.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (3.20.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (1.2.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (6.0.3)
Requirement already satisfied: shellingham in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (1.5.4)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (4.67.3)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (0.21.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (4.15.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub) (0.16.0)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.12/dist-packages (from typer-slim->huggingface_hub) (8.3.1)
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.20.3)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.4.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers) (0.21.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.2.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.28.1)
Requirement already satisfied: shellingham in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.5.4)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (4.15.0)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.12/dist-packages (from typer-slim->transformers) (8.3.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (0.16.0)

In [2]:
from datasets import Dataset, DatasetDict
import pandas as pd
df1 = pd.read_csv("Rajasthan_metadata.csv")
df2 = pd.read_csv("Rest_metadata.csv")
df1 = df1[['Name','Caste','Clustered_Caste']]
df2 = df2[['Name']]
df1['Caste'] = df1['Caste'].fillna('Unknown')
df1['Clustered_Caste'] = df1['Clustered_Caste'].fillna('Unknown')

name1 = []
caste1 = []
cluster1 = []
name2 = []
for i in range(len(df1)):
  name1.append(df1['Name'].iloc[i])
  caste1.append(df1['Caste'].iloc[i])
  cluster1.append(df1['Clustered_Caste'].iloc[i])
for i in range(len(df2)):
  name2.append(df2['Name'].iloc[i])
dict1 = {'Name':name1,'Caste':caste1}

dict2 = {'Name':name2}
train_dataset = Dataset.from_dict(dict1)
test_dataset = Dataset.from_dict(dict2)
dataset = DatasetDict({
    "train": train_dataset,
    "test": test_dataset
})

from sklearn.preprocessing import LabelEncoder
le_caste = LabelEncoder()
dataset["train"] = dataset["train"].remove_columns("Caste").add_column(
    "label_caste", le_caste.fit_transform(dataset["train"]["Caste"])
)
print(dataset)
num_labels = len(le_caste.classes_)
print(num_labels)

DatasetDict({
    train: Dataset({
        features: ['Name', 'label_caste'],
        num_rows: 5000
    })
    test: Dataset({
        features: ['Name'],
        num_rows: 666
    })
})
875

In [3]:
print(dataset)

DatasetDict({
    train: Dataset({
        features: ['Name', 'label_caste'],
        num_rows: 5000
    })
    test: Dataset({
        features: ['Name'],
        num_rows: 666
    })
})

In [4]:
from huggingface_hub import login

login()

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

In [6]:

from transformers import AutoTokenizer, AutoModelForSequenceClassification
tokenizer = AutoTokenizer.from_pretrained("ai4bharat/indic-bert")
def tokenize(examples):
    return tokenizer(
        examples["Name"],
        padding="max_length",
        truncation=True
    )

dataset = dataset.map(tokenize, batched=True)
model = AutoModelForSequenceClassification.from_pretrained(
    "ai4bharat/indic-bert",
    num_labels=num_labels
)
import numpy as np

config.json:   0%|          | 0.00/507 [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/5.65M [00:00<?, ?B/s]

Map:   0%|          | 0/5000 [00:00<?, ? examples/s]

Map:   0%|          | 0/666 [00:00<?, ? examples/s]

pytorch_model.bin:   0%|          | 0.00/135M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/25 [00:00<?, ?it/s]

AlbertForSequenceClassification LOAD REPORT from: ai4bharat/indic-bert
Key                              | Status     |
---------------------------------+------------+-
predictions.decoder.bias         | UNEXPECTED |
sop_classifier.classifier.weight | UNEXPECTED |
sop_classifier.classifier.bias   | UNEXPECTED |
predictions.LayerNorm.weight     | UNEXPECTED |
predictions.LayerNorm.bias       | UNEXPECTED |
predictions.dense.bias           | UNEXPECTED |
predictions.dense.weight         | UNEXPECTED |
predictions.bias                 | UNEXPECTED |
predictions.decoder.weight       | UNEXPECTED |
classifier.weight                | MISSING    |
classifier.bias                  | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [7]:
print(dataset)

DatasetDict({
    train: Dataset({
        features: ['Name', 'label_caste', 'input_ids', 'attention_mask'],
        num_rows: 5000
    })
    test: Dataset({
        features: ['Name', 'input_ids', 'attention_mask'],
        num_rows: 666
    })
})

In [8]:
!pip install evaluate

Collecting evaluate
  Downloading evaluate-0.4.6-py3-none-any.whl.metadata (9.5 kB)
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.0.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.0.2)
Requirement already satisfied: dill in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.2.2)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.32.4)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from evaluate) (3.6.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.70.16)
Requirement already satisfied: fsspec>=2021.05.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (1.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from evaluate) (26.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (3.20.3)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (18.1.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (3.13.3)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (1.2.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (0.28.1)
Requirement already satisfied: shellingham in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (1.5.4)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (0.21.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2026.1.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2025.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.22.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (4.12.1)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (0.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->evaluate) (1.17.0)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.12/dist-packages (from typer-slim->huggingface-hub>=0.7.0->evaluate) (8.3.1)
Downloading evaluate-0.4.6-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 8.3 MB/s eta 0:00:00

model.safetensors:   0%|          | 0.00/135M [00:00<?, ?B/s]

Installing collected packages: evaluate
Successfully installed evaluate-0.4.6

In [9]:
import evaluate
metric = evaluate.load("accuracy")
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    # convert the logits to their predicted class
    predictions = np.argmax(logits, axis=-1)
    return metric.compute(predictions=predictions, references=labels)
from transformers import TrainingArguments, DataCollatorWithPadding # Re-add DataCollatorWithPadding

training_args = TrainingArguments(
    output_dir="yelp_review_classifier",
    eval_strategy="epoch",
    push_to_hub=False,
    warmup_steps=0.13,
    learning_rate = 5e-5,
    adam_beta1=0.9,
    adam_beta2=0.999,
    adam_epsilon=3e-8,
    weight_decay=0.001,
    lr_scheduler_type = "linear",
    num_train_epochs=50
)
from transformers import Trainer

split = dataset["train"].train_test_split(test_size=0.1)
train_dataset = split["train"]
eval_dataset = split["test"]
print(train_dataset)
train_dataset = train_dataset.rename_column("label_caste", "labels")
eval_dataset = eval_dataset.rename_column("label_caste", "labels")

train_dataset.set_format(type='torch', columns=['input_ids', 'attention_mask', 'labels'])
eval_dataset.set_format(type='torch', columns=['input_ids', 'attention_mask', 'labels'])

data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=eval_dataset,
    compute_metrics=compute_metrics,
    data_collator=data_collator
)

trainer.train()

pred_results = trainer.predict(dataset["test"])
pred_labels = np.argmax(pred_results.predictions, axis=-1)
pred_categories = [le_caste.classes_[i] for i in pred_labels]
dict2["Caste"] = pred_categories
print(dict2)

Downloading builder script: 0.00B [00:00, ?B/s]

Dataset({
    features: ['Name', 'label_caste', 'input_ids', 'attention_mask'],
    num_rows: 4500
})

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'Name': ['ABHAY', 'PANCHAL MANOJ ', 'GONSALVES SUNNY', 'AMRIT', 'BAISOYA RISHABH', 'GIRI HEMANT', 'KADIAN YOGESH', 'SINGH HARBHEJ', 'SINGH JOGA', 'SHARMA SACHIN', 'BAJAJ RITIK', 'SINGH BARJINDER', 'KUMAR ANIL', 'PATEL PRITESH MUKESHBHAI', 'JAIN HARSHIT BABULAL', 'SINGH VIKRAMJEET', 'SANGWAN KAPIL', 'SINGH SATINDERJEET', 'SANDHU HARWINDER SINGH', 'SINGH RANDEEP', 'KOLANJA MOHAMMAD RAFEEQ', 'PURUSHAN SUDHEESH KUMAR', 'HAIDER SYED MUHAMMAD ARSHIYAN', 'NANAVATI ADITYA', 'SINGH GURJINDER', 'GUPTA VIKASH', 'SANDHU SHAMINDER SINGH', 'RAIJADA KAVALJITSINH MAHENDRASINH', 'SINGH HARSAHIB', 'ANGOM SANATOMBA SINGH', 'PUKHRAMBAM SAMANANDA SINGH', 'KSHETRIMAYUM BROJEN SINGH', 'TAKHELAMBAM RAGHU', 'THOKCHOM GANDHI SINGH', 'SULTAN AYAZ MOHAMMED', 'ARMAR MOHAMMAD SHAFI', 'SINGH KARANVIR', 'SINGH AVTAR', 'SINGH HARMEET', 'RANPARIYA JAYSUKH', 'SINGH JANG BAHADUR', 'SINGH GURMIT', 'BHANSALI MIHIR RASHMI', 'SINGH GURPREET', 'SINGH MEHENGA', 'LAMKANG STARSON', 'MOIRANGTHEM TAMBA', 'KHURAIJAM MAIPAK', 'MUNSHI SHAIKH ZAHIDMIYA', 'CHERIYA VEETTIL SADIQUE', 'GOTTIPARTHI SRINIVAS', 'AHMED SADAB', 'SHEIKH ABU RASID', 'HUSSAIN ANWAR', 'RAJBHAR BALARAM', 'ISHAQI SALIM', 'MOHD KHALID', 'BEG MIRZA SHADAAB', 'ALAM DR. SHAHNAWAZ', 'ARMAR ABDUL KHADER SULTAN', 'NEHRA AJAY', 'SINGH DEVESH KUMAR', 'IQBAL L IWANTHABA', 'PATIL RUDRA', 'LIMKAR PRAVEEN', 'CHOUDHARY MOHSIN', 'KAGZI FAYAZ', 'T R CALVIN RAINGAM', 'BAINS AMANDEEP SINGH', 'SHAHABANDRI RIYAZ AHAMED', 'SHAIKH HASSAN LUKMAN', 'JAMATIA COMREDPADA', 'JOSEPH THARAKAN PARRAYIL GEORGE', 'KHAN MOHAMMED SHOEB', 'DOLA SALIM', 'SINGH AMRIK', 'SINGH GURTEJ', 'AHMED FAHIM', 'PATEL BHARATBHAI VIHABHAI', 'MODI NIRAV DEEPAK', 'SINGH RAJ', 'CHAUHAN RAM', 'TAMANG JAIY', 'THOUDAM SOMORENDRO SINGH', 'BHUTHAM GOVINDU', 'MALBARI ABDUL RASHEED HUSAIN SHEIK', 'SHETTY BALAKRISHNA', 'BHAT ZAFFAR HUSSAIN', 'SHERA UMAR FAROOQ', 'DAR NAZIR AHMAD', 'NAG ARUP', 'GOSAIN PRAMOD', 'BABU NURBASHA MOHAMMAD', 'MOHAMMED ABU SAAD', 'DEEPAK RANJAN', 'YOGISH', 'DIAS CLEMANT VICTOR', 'KUMAR SAJJAN', 'PATIDAR RAMCHANDRA KALSANGARA', 'DANGE SANDEEP VASUDEV', 'DEBBARMA BUDHRAI', 'SAYYED MUZAKKIR MUDDASSAR HUSAIN', 'GURSHARAN SINGH KALER', 'CHOUDHARY SANJAY KUMAR', 'PATEL RAFIQ', 'VIJAY SHYAM SHETTY', 'BHATKAL IQBAL', 'BHALLA RAKESH MOHAN', 'SREEDHARAN SUDHIN KUMAR', 'MARQUES INACIO', 'DEVDIWALA FAROOQ', 'SINGH RAVI PRAKASH', 'SINGH BHAGWANT', 'CHAURASIYA BRIJ BHUSHAN', 'DAWREY RIZWAN MOHAMMAD', 'SEKAR', 'AMARJIT SINGH AMBA', 'SHARIFKHAN PATHAN', 'DEBBARMA SACHINDRA', 'FAROOQUI ABDUL ARIF', 'SHARMA SURESH', 'CHOUGULE IRFAN', 'CHANDOK SURENDER SINGH', 'SHEIK DAWOOD SHAHUL HAMEED', 'KSHETRIMAYUM NOYON SINGH', 'NAMOIJAM OKENDRO SINGH', 'SUMI NIKI', 'BANGARD NAVAL KISHORE', 'SIDDIQ ABUBAKKAR', 'SUKHMINDER SINGH BAINS BHOLA', 'DEEPAK MANIKAN', 'KHAN GULAM NABI', 'DAR MANZOOR AHMAD', 'MAQBOOL PANDIT MOHD', 'NARENGBAM MARIJIT SINGH', 'VENKATA PRAVEEN KUMAR RAJULAPATI', 'NICOL TAMANG', 'JAGDISHBHAI PUNJIRAM', 'GHORI MOHAMMED FARHATULLAH', 'PATEL NATUBHAI SATABHAI', 'PATEL DILIPBHAI BABUBHAI', 'BATRA DAMINDER SINGH', 'SHANKARAN RAVI', 'BANGER JASWINDER SINGH', 'SYED ALMAS MAHARAJ', 'HANIF TIGER', 'AGRAWAL SURENDRA', 'GADGIL NANDAN PRABHAKAR', 'BARUAH PARESH', 'SHAIKH SHAKEEL', 'SHAIKH ANIS', 'KASKAR DAWOOD IBRAHIM', 'SIVARAMA KURUP SUKUMARAN', 'VISHWANATHA SHETTY', 'SINGH GURUDEV', 'PREM SETHI', 'ANSARI TAHER', 'MOHD YUSUF SHAH', 'SAYED ARIF', 'DOSA MOHAMED AHMED', 'BEDI SURENDER SINGH', 'CHANDOK HARLEEN KAUR', 'NAUSHA KADEEJATH', 'STANLY VARGHESE BHUVANESWARI', 'EDADAN OMANA', 'ABDUL ASIF ABDUL SADIK', 'ABDUL GAFFAR ABDUL KADAR', 'ABDUL KHAN AYUB KHAN', 'Abdul Rafique Abdul Kabir', 'ABDUL SAJID ABDUL SAMAR', 'ABDUL SALIM ALIAS BADSHAHA ABDUL SALAM', 'ABDUL SHAKIR ALIAS ABDUL RAZAK', 'ABDUL WAJID ABDUL KHALID', 'ABDUL WASIM ABDUL SALAM', 'ABHISHEK VIVEK DESHMUKH', 'AJAY ARUN JUNGHARE', 'AJAY PRAKASH DABHADE', 'AKASH HARIBHAU PARTEKI', 'Akash Ramesh Wankhade', 'AKHILESH JAYANTILAL AADTIYA', 'Akshay Alias Shirish Shivdatta Mate', 'AKSHAY SURESH CHARHATE', 'AMAR ARVIND BONDE', 'AMAR BHARAT WAWER', 'AMIT RAMNARAYAN TIWARI', 'AMOL BABURAO DANGE', 'AMOL BAPURAO DANGE', 'AMOL DAYANAND WASNIK', 'AMOL DYANESHWAR RAUT', 'ANIL BHAGWATRAO MOHANKAR', 'ANIL DASHRATH KHADSE', 'ANIL RAMRAO WANKHADE', 'ANKUSH WASUDEV THAKARE', 'ANSAR KHAN ALIAS TANTYA YUSUF KHAN', 'Ansar Khan Mahommad Khan', 'ARSHID KHAN RASHID KHAN', 'ARUN RAMDAS YEDATKAR', 'ASHISH BABAN DESHMUKH', 'ASHOK ALIAS CHOTU SAHDEVRAO INGALE', 'ASHOK SHYAMA BHOSALE', 'ASHWIN ASHOK WANKHADE', 'ATAULLAH KHAN BISMILLA KHAN', 'ATUL MURALIDHAR NAIK', 'AVINASH ASHOK BHUYAR', 'AZAHAR BEIG KADAR BEIG', 'BABARAO DADARAO HIVRALE', 'BABLU KHAN HASIL KHAN', 'BADSHAH AJABSING TANK', 'BADSHAHASINGH AJABSINGH TANK', 'BADSHAHASINGH AJABSINGH TANK', 'BALU GULAB MAHALLE', 'BANDYA KISAN KALE', 'BARAKYA ALIAS HANSRAJ PAWAR', 'BARKYA ALIAS RAJHANS JARTARI PAWAR', 'BATKYA JALTARI PAWAR', 'BHARAT MOHAN DIVATE', 'BHOLU ALIAS SHAKIRNUR MOHAMMAD', 'BHOLU MORE', 'BHURE KHAN RAFIQUE KHAN NOOR KHAN', 'Bhushan Pradip Baseriya', 'BUNTY ALIAS RAVI SHYAM ATHIYA', 'BUNTY SHOKRAO PAWAR', 'CHARAN MANIK LADE', 'DADARAO HIRAMAN RANGARI', 'DADASING ALIAS RAJASING AJABSING TANK', 'DARASING KISAN MALAVE', 'DEELIP KISANRAO WAGH', 'DEELIP RAM KORDE', 'DEELIP SHIVACHAND CHUDIWALA', 'DEEPAK MADAN PATIL', 'DHANRAJ RAMASWAMI ZIRPILLAI', 'DILBARSING JOHANSING TANK', 'DILDAR KHAN SATTAR KHAN', 'DILIP KISAN PUNASE', 'DINESH NAMDEV KHEDKAR', 'DINESH NAWANDAR', 'DIPAK ALIAS NAKTYA GENDALAL GUPTA', 'DIPAK SHRIRAM KALE', 'DIWAKAR GOWARDHAN KHADSE', 'DYANESHWAR VITTHAL KALANE', 'FATTUSINGH INDRASINGH MILL', 'FIRDAUS KHAN MEHABUB KHAN', 'GAFFARALI SATTARALI', 'GAJANAN ARUN ATRAM', 'GAJANAN CHALISA BHOSALE', 'GAJANAN DADARAO NEWARE', 'GAJANAN GOPALRAO INGOLE', 'GAJANAN HIMMATRAO KARALE', 'GAJANAN PRALHAD KALPANDE', 'GANESH BABARAO PURI', 'GAURAV GAJANAN KAMBE', 'GAUTAM MOTIRAM GHODESWAR', 'Golu Alias Swapnil Mukund Shinde', 'GOPAL BABAN SOLANKE', 'GOPAL MADHUKAR THORAT', 'GOPAL MADHUKAR THORAT', 'GOVIND NARAYAN SAHU', 'GUDDU ALIAS SHEIKH ANSAR SHEIKH SATTAR', 'GULAM HASAN AULAD HUSAIN', 'HARIKESH ALIAS GUDDU MADAN KATTILWAR', 'HARSHAL ALIAS BALA MURLIDHAR GAWALE', 'HEMRAJ BHALALIYA SASI', 'IMRAN KHAN ALIAS BABLU ARIF KHAN', 'IRFAN KHAN SHARIF KHAN', 'IRFAN KHAN SHARIQUE KHAN', 'IRFANUDDIN GULFARAZUDDIN', 'JACKY ALIAS JAYKISAN RUPRAO PARADE', 'JANARDHAN ALIAS JANYA ALIAS JOHNY RAMRAO WAGHMARE ALIAS RAJESH SAANE', 'JARNAILSINGH ALIAS RAHULSINGH JYOGENDRASINGH TANK', 'JAY VIJAYKUMAR SHARMA', 'JAYANDRA PRAKASH KALE', 'JAYANT PRAKASH KALE', 'JAYPRAKASH NANDLAL MARIYA', 'JITENDRA AJAY DHOKE', 'JITU ALIAS JITENDRA RAMRAO BHAGAT', 'JYOTISINGH UMRAOSINGH BABARI', 'Kailash Kuwarsingh Bheel', 'KAILASH RATANSING PAWAR', 'KALYA ALIAS RAKESH MANJU BABA TAMBOLE', 'KARAN CHOKHELAL SEN', 'KISAN SHESHRAO HANDE', 'KULDEEPSINGH DARSHANSINGH JUNNI', 'LAL ALIAS HAFIZ SHAH HABIB SHAH', 'LAXAM AMBADAS SOLANKE', 'LAXMI VIRANNA ZHIRPILLAI', 'LOKESH JARTARI PAWAR', 'MAHADEV BHIMRAO GHORMADE', 'MAHESH ALIAS AJAY RAJKAMAL SASI', 'MAHESH CHAUBITRAM JIVTANI', 'MAISUR TABJUL BEIG SAFJALUL BEIG', 'MANGA VIRANNA ZIRPILALU', 'MANGESH ALIAS KALOTYA DEELIP WAGHMARE', 'MANGESH RAMDAS MUNDANE', 'MANGESH TULSHIRAM RAUT', 'MANISH ALIAS BABLU KESHAV NAGPURE', 'MANISH ROSHANLAL PUROHIT', 'MANOJ BABULAL SOLANKE', 'MANOJ LAXMAN GONDANE', 'MEHAMUD SHAH MUSTAFA SHAH', 'MEHBUB KHAN HAYAT KHAN', 'MOHABBATSINGH KAURSINGH THAKUR', 'MOHAMAD IMRAN MOINUDDIN', 'MOHAMAD JAMIL ALI NUSARAT ALI', 'MOHAMAD VASIM ISMAIL', 'MOHAMMAD JAWED MOHAMMAD MIRZA', 'MOHAMMADSINGH PARVATSINGH', 'MOHSEEN KHAN HAMID KHAN', 'MOMIN KHAN RAHEMAT KHAN', 'MUKESH LAKSHAMSINGH THAKUR', 'MUKUND DURYODHAN WAWARE', 'NAGESH NAMDEV KHEDKAR', 'NAJAKAT ALIAS NAJJA SHEIKH BABA', 'NARAYAN ALIAS ARYAN KALURAM DEVKAR', 'NARAYAN KISAN PATAKE', 'NARENDRA PRAKASH DHAGE', 'NARESH PADMAKAR NANDESHWAR', 'NASIN KHAN ALIAS NAJJA RASHID KHAN', 'NIJAMUDDIN AJIJ KHAN', 'NIKHIL VIJAY TIKALE', 'NILESH DEELIP POTFODE', 'NILESH HARIVIJAY UGHADE', 'NILESH TUKARAM CHAVHATE', 'NITIN MADHUKAR MESHRAM', 'NITIN MAROTRAO NALHE', 'NITIN NARESH CHAVHAN', 'NITU NATTHU DAWANDE', 'OM MADAN CHAUDHARI', 'OMPRAKASH BHARAT BHATAKAR', 'PANJAB UTTAMRAO GAJBHIYE', 'PANKAJ ALIAS DEBU AVADHUT GAJBHIYE', 'PANKAJ GANESH BHURAI', 'PANKAJ RAJU GONDANE', 'PANKAJ RAMDAS DHOKE', 'PANKAJ SURESH TAYADE', 'PAVAN ALIAS BHOLU SHANKAR BARAD', 'PAVAN ANIL TIDAKE', 'PAVAN DINKAR GALE', 'PAVAN PRAKASHCHANDRA MATWANI', 'PAVAN RAMESH TOPALE', 'PINTYA KISAN BHANDE', 'PRABHAKAR NAGORAO BHOWALE', 'PRADIP PANDURANG SHENDE', 'PRAKASH ALIAS ANTHONY ALIAS THOMAS DHANDAR', 'PRAKASH CHANDRBHAN BENDRE', 'PRAKASH DINESH ATHAVALE', 'PRAKASH JIYALDAS MANWANI', 'PRALHAD DHNYANESHWAR GAYAKWAD', 'PRAMOD DEVRAO BANSOD', 'PRAMOD MAHADEV DHANADE', 'PRAMOD UTTAM DHOKE', 'PRATIK DHANRAJ ZADE', 'PRATIK NAMDEO SHINDE', 'PRAVIN ALIAS PINTYA BHIMYA BANSOD', 'PRAVIN TULSHIRAM KADU', 'PRITAM PANDURANG SURWANSHI', 'PRUTHVI ASHOK WANKHADE', 'RAHAMAT KHAN BISMILLA KHAN', 'RAHUL AMBADAS GETHE', 'RAHUL AMBADAS GETHE', 'RAHUL SUDHAKAR KHOBRAGADE', 'RAJABHAU BOBADE', 'RAJESH BABULAL SOLANKE', 'RAJESH NARAYAN BITAKARI', 'RAJU DATTOPANT ATHAVALE', 'RAJU HOTCHAND ADWANI', 'RAJU SHARAD KALE', 'Rakesh Gopal Gehalod', 'RAMJAN SHAHA TUKDU SHAHA', 'RANU ALIAS RANDEEP CHAINSUKH CHANGANI', 'RASHID KHAN ALIAS MUNGUS GAUSADAR KHAN', 'RAVI ALIAS MAMA LALLUN KHURKHURIYA', 'RAVI CHARAN PATIL', 'RAVI NARAYAN KHADASE', 'RAVINDRA ALIAS GOND SHIVDAS DHOKE', 'RAVINDRA HARIDAS PANEKAR', 'REHANA BANO AHAMAD SHAH', 'Rohit Ganeshrao Ajabe', 'ROSHAN DHASAKAT', 'ROSHAN SANJAY DESHMUKH', 'ROSHAN SURESH KHOBRAGADE', 'ROSHAN VINAYAK ROHANKAR', 'ROSHAN WASUDEV DHASKAT', 'RUPESH BANGADE', 'RUSHIKESH TULSHIRAM KANTALE', 'SACHIN BHASKAR LANJEWAR', 'SACHIN DINKAR CHAUDHARI', 'SACHIN SHRIKRUSHNA DESHMUKH', 'SACHIN WALKHADE', 'SAFDAR BEIG AZAGAR BEIG', 'SAGAR JANARDHAN GOGATE', 'SAGAR JANRAO WANKHADE', 'SAGAR NANAJI WANKHADE', 'SAGAR NARAYAN KHANDARE', 'SAGARSING MAYASING TANK', 'SAIF AHAMAD FARUK AHAMAD', 'SAIYAD ASIF SAIYAD BHURU', 'SAIYAD NIYAJ SAIYAD MUZHAFAR', 'SAIYAD SHAFIQUE SAIYAD RAFIQUE', 'SAIYAD SHAKIR SAIYAD BHURA', 'SALEM DASU GOGALU', 'SALIM KHAN ALIAS SALLU RAFIQUE KHAN', 'SAMAD SHAUKAT SAMAD ABDUL', 'SANDIP DADARAO PAHADAN', 'SANDIP KISAN VAIDYA', 'SANDIP RAMESH RAUT', 'SANDIP SHANKAR KSHIRSAGAR', 'SANGAM HANUMANT MESHRAM', 'SANGITA JADHAV', 'SANJAY ALIAS FANTER DHANSUKH BUDHWANI', 'SANJAY AMBADAS THOSARE', 'SANJAY DEELIP GHODE', 'SANJAY SHANKAR AWARE', 'SANTOSH BANSOD', 'SANTOSH KESHAV KINNAKE', 'SANTOSH SHALIKRAM GAYAKWAD', 'SATISH ALIAS GOLU PURUSHOTTAM SIDAM', 'SATISH ALIAS SATTYA UKADRAO KUROTIYA', 'SATISH BHAGATSINGH SOLANKE', 'SATTYA ALIAS SATISH UKANDRAO KUTORIYA', 'SHAKIR NUR MOHOMMAD KHAN', 'SHAMIULLA KHAN HAFIZULLA KHAN', 'SHAMMI SHAHA MURAD SHAHA', 'SHANKAR SUBHASH BANSOD', 'SHARIK ALI ASHAK ALI KHAN', 'SHASHIKANT PRABHUDAYAL UPADDHYAY', 'SHASHIKUMAR SAHEBRAO TATTE', 'SHEIKH ANSAR NIYAJ ALI', 'SHEIKH ARIF ALIAS GUDDU SHEIKH YUSUF', 'SHEIKH ARIF SHEIKH MUSUD', 'SHEIKH ASIF SHEIKH GUDDU', 'SHEIKH AYUB SHEIKH IBRAHIM', 'SHEIKH CHAND SHEIKH BHURU', 'SHEIKH CHHOTU ARIF SHEIKH DILAWAR', 'SHEIKH CHOTU SHEIKH DILAWAR', 'SHEIKH FIROZ SHEIKH YAKUB', 'SHEIKH GOLU SHEIKH BABA', 'SHEIKH GOLU SHEIKH KADAR', 'SHEIKH HAMID ALIAS MOTU SHEIKH HANIF', 'SHEIKH HAMID ALIAS MOTU SHEIKH HANIF', 'SHEIKH HASAN SHEIKH HUSAIN', 'SHEIKH IRAFAN SHEIKH BISMILLAH', 'SHEIKH JAFAR SHEIKH KARIM', 'SHEIKH JAVED SHEIKH BHURU', 'SHEIKH JAWED ALIAS DADU SHEIKH SABIR', 'SHEIKH JAWED SHEIKH BHURU', 'SHEIKH MATIN SHEIKH MEHABUB', 'SHEIKH RAFIQUE NABIULLA SHEIKH ALIAS SHEKHAR PATIL', 'SHEIKH RIZWAN ALIAS MUNNA MOBILE SHEIKH JALIL', 'SHEIKH SABIR SHEIKH IMAM', 'Sheikh Salman Sheikh Shakur', 'Sheikh Shahid Sheikh Chand', 'SHEIKH TOUFIQUE SHEIKH RAFIQUE', 'SHIVA ALIAS SHIVAJI VITTHAL BHOSALE ALIAS BHOLE', 'SHOBI ALIAS SHOHEB BABBU SARPANCH', 'SHRIKRUSHANA PINTYA DEVIDAS GAHUKAR', 'SHUBHAM GAJANAN SAYANKE', 'SHYAM GAJANAN PURI', 'SHYAM MADAN PATHAK', 'SINNA CHINNA ATAPALLI', 'SONYA ALIAS MANGESH BHIMRAO CHANDURKAR', 'SUBODH BHIMARAO DHAKADE', 'SUDHIR DADARAO PUND', 'SUDHIR LAXMAN JAVANJAL', 'SUDHIR SURESH LAHUPANCHANG', 'SUHAS ALIAS PRAKASH ASHOK JOSHI', 'SUNIL JAYDEV MESHRAM', 'SUNIL PRAKASH GULSUNDARE', 'SUNIL SHANKARRAO MATE', 'SUNIL SHYAMRAO UKE', 'SUNNY SUNIL BIJAVE', 'SURAJ GAJANAN DESHKAR', 'SURAJ PURUSHOTTAM GUPTA', 'SURENDRA RAOSAHEB KORE', 'SURENDRA UDHAVRAO WAKODE', 'SURESH PRAKASH RANGARI', 'SURESH SUDHAKAR GANDHE', 'SUSHANT ARUN GANJARE', 'SUSHIL ALIAS KHANDYA WANKHADE', 'SUYASH CHANDRASHEKHAR DORLE', 'SWAPNIL MOTIRAM MESHRAM', 'Swapnil Vinay Bangre', 'TAANYA ALIAS TANAJI VITTHAL BHOSALE', 'TIRUMALLI WALKISAN ATAPALLI', 'UJWAL ALIAS SONU SHEKHAR KAMKARE', 'UMESH BHUJANGRAO MAHALLE', 'VASIM KHAN YUSUF KHAN', 'VIJAY NAJUK INGALE', 'Vijay Pandurang Raybole', 'VIJAY SANJAY SURYAWANSHI', 'VIJAY TULASHIRAM KALE', 'VIKAS RAMJI CHAPALKAR', 'VIKKY ALIAS ASHOK GANOSKAR', 'VIKKY DHANARAJ KHANDARE', 'VIKKY RAJENDRA GADLING', 'VINOD ARUN KOTHE', 'VIRANNA BANKKATAPPA ZIRPILALU', 'VISHAL ARUN PAWAR', 'VITTHAL SHANKARAO MANKAR', 'Vivek Alias Bikku Ravindra Pande', 'VIVEK ALIAS BODYA VINAYAK NIRMAL', 'WAHID KHAN SAID KHAN', 'WAMAN JAGAN NAIK', 'WASANT SHANKAR CHAUDHARI', 'YOGESH ALIAS LAKHAN RAMESH WANKHADE', 'YOGESH GOVIND TAYADE', 'YUSUF ALI ASHAF ALI KHAN', 'ZAHIR SHEKHU KHURSHID ABBAS', 'ZAKIR HUSAIN JINNATALI', 'RAJESH KUMAR', 'Shri Deepankar Barman', 'Shr Hasen Ali', 'Shri Mohibul Prodhani', 'Azirul Islam alias Aziul Hoque', 'Shri Sunil Gogoi', 'Shahabaj Jakaria Shikdar', 'Ferdynald Kharkamni', 'Shri Arun Kumar Jain', 'Shri Santanu Mizar', 'Shri Amit Paul', 'Shri Lakstar Khariap', 'Shri Pujam Gurung', 'Shri Tilok Dorjee', 'Shri Mukhiya Singh', 'Shri Jhuggo Jasoda', 'Shri Shanborlang Rani alias Dengdeng', 'Shri Rohit', 'Bringo Lyngdoh', 'Nayan Bhattacharjee', 'Shri Sandeep Sunar', 'Shri Din Dayal Sharma', 'Shri Harlal Jat', 'Shri Majidul Khan', 'Shri Dilip Baspor', 'Shri Eyahia Ahmed', 'Shri Biswajit Yadav', 'Shri Amit Ghosh', 'Shri Mithun Sharma', 'Shri Nihar Ranjan Bhattachariya ', 'Shri Santosh Hajong ', 'Smti Balarisa Nengnong', 'Shri Diganta Kumar Adhikari', 'Shri Dilip Kumar', 'Shri Arjun Burman', 'SHRI DANIEL HAWK ', 'Shri Ramesh Gurung ', 'Smti Anandi Chapagai', 'Shri Khimananda Chapagai', 'Biswng Prasad Chattri', 'Shri Tapan Ojha', 'Shri Manseng D Sangma', 'Shri Lalit Dey', 'Shri Nur Mohmmed', 'Shri Asraful Ali', 'Shri Babeshor Kalandi', 'Shri Rex Briller R Marak', 'Miss Eunice Zimik', 'Shri Prema', 'Shri Shynsharlang Thongni', 'Shri Sumon Namo ', 'Smti Jesica Kharkongor ', 'Shri Mukesh Sangma', 'Bhim Singh', 'Shri Konesshon Rodborn ', 'Shri Thoudam Prasanta Singh  ', 'Chatu', 'Madhurendra Singh', 'Rousan', 'Bablu Rewani', 'Sunil Madni', 'Tribeni Prasad', 'Guljar Ansari', 'Samim', 'Kishore Mondal', 'Sakir Ansari', 'MD. SIRAJ', 'MD. NAUSHAD KHAN', 'MD. AKTAR KHAN', 'AKBAR KHAN', 'PABAN KUMAR YADAV', 'AMIT KUMAR YADAV', 'KALIYA KURMI', 'PINTU DEY', 'DHARMENDRA', 'UJJAL BOURI', 'MD NAWSAD', 'CASHIER', 'SK. LAL', 'RAKESH HELA', 'RAJESH VERMA', 'NANDA BOURI', 'KRISHNA DAS', 'KARA RAJ BANGSI', 'KRISHNA YADAV', 'BAIJU PRASAD RAM', 'LOKE NATH MUKHERJEE', 'SUBRATA SARKAR', 'PRITAM DAS', 'RANJIT HELA', 'RAJU RUIDAS', 'RAJU BOURI', 'RAHUL YADAV', 'PINTU RUIDAS', 'LAXMAN LAMA', 'LACHMI SAHANI', 'KARKAT DAS', 'JOGI DAS', 'GOUR SENGUPTA', 'BHALTU PASI', 'BESAN RUIDAS', 'BALDEV TURI', 'AUSTA RUIDAS', 'ANAND PASWAN', 'TIPU ANSARI', 'SUSHIL RAM', 'SURAJIT SARKAR', 'SK TAHIR', 'SK  SAMSOL', 'SK MOHIBUL', 'SK KHALID', 'SK IMAMUL', 'SK ILIAS', 'SK ASHRAF', 'SK AKHTAR', 'SK ABAR ALI', 'SARUDDIN', 'PRADIP KR TIWARI', 'MRINAL KANTI GHOSH', 'MOHAN RUIDAS', 'MD SHANAWAR', 'MD RIZWAN', 'MD NOUSAD', 'MD-IMTIYAJ', 'MANOJ-DOM', 'UTPAL-GHOSH', 'JITEN-PAUL', 'BADYANATH MONDAL', 'BURO BOURI', 'BIRJU PASWAN', 'SANJOY KR SUKLA', 'Mithilesh Kumar Singh', 'Khusbu', 'Rajesh Paswan', 'Manoj Mallick', 'Amar Mahato', 'MOHAN', 'Kanahi Bouri', 'Nimai Ruidas', 'Sanjoy Ruidas', 'Santosh Rewani', 'Sushil', 'Srimanta Ruidas', 'Manik Das', 'Rahul', 'RAJU', 'Gour', 'Raju Bauri', 'Besan', 'Bhaltu', 'Kartak Das', 'Jogi', 'Lachmi', 'Anand Paswan', 'Austa', 'Astik', 'BALDV TURI', 'LAXMAN'], 'Caste': [np.str_('MALI'), np.str_('MEENA'), np.str_('VALMIKI'), np.str_('KANJAR'), np.str_('MEENA'), np.str_('MAHAJAN'), np.str_('NAYAK'), np.str_('RAISIKH'), np.str_('RAISIKH'), np.str_('meena'), np.str_('mev'), np.str_('Jat sikh'), np.str_('MEENA'), np.str_('JAIN'), np.str_('BRAHMAN'), np.str_('RAJPOOT'), np.str_('MALI'), np.str_('jat'), np.str_('RAISIKH'), np.str_('RAJPUT'), np.str_('musalman'), np.str_('JAAT'), np.str_('MUSALMAN'), np.str_('KHATIK'), np.str_('JATSIKH'), np.str_('Mahajan'), np.str_('meena'), np.str_('PANJABI'), np.str_('RAJPUT'), np.str_('RAJPUT'), np.str_('JAT'), np.str_('RAJPUT'), np.str_('NAYAK'), np.str_('RAJPUT'), np.str_('MUSLIM'), np.str_('MUSLIM'), np.str_('RAJPUT'), np.str_('GURJAR'), np.str_('JATSIKH'), np.str_('JAAT'), np.str_('RAJPUT'), np.str_('JATSIKH'), np.str_('MOMDAN'), np.str_('jat'), np.str_('RAJPUT'), np.str_('KANJAR'), np.str_('Rajput'), np.str_('MEV'), np.str_('muslim'), np.str_('MUSALMAN'), np.str_('SONI'), np.str_('PATHAN MUSALMAN'), np.str_('musalman'), np.str_('MUSALMAN'), np.str_('SINDHI'), np.str_('MUSLIM'), np.str_('musalman'), np.str_('MUSLIM'), np.str_('muslim'), np.str_('muslim'), np.str_('BRAHMAN'), np.str_('RAJPUT'), np.str_('MUSALMAN'), np.str_('jat'), np.str_('SONI'), np.str_('muslim'), np.str_('MUSLIM'), np.str_('BRAHMAN'), np.str_('RAYSIKH'), np.str_('MUSLIM'), np.str_('musalman'), np.str_('JAIN'), np.str_('KUMAWAT'), np.str_('muslim'), np.str_('muslim'), np.str_('RAJPUT'), np.str_('RAJPUT'), np.str_('PATHAN MUSALMAN'), np.str_('BRAHAMIN'), np.str_('ARODA'), np.str_('RAJPUT'), np.str_('JAT'), np.str_('DESWALI MUSALMAN'), np.str_('RAJPUT'), np.str_('SONI'), np.str_('MUSLMAN'), np.str_('MAHAJAN'), np.str_('MUSALMAN'), np.str_('MUSLIM'), np.str_('MUSLMAN'), np.str_('balai'), np.str_('AHIR'), np.str_('MUSALMAN'), np.str_('muslim'), np.str_('HARIJAN'), np.str_('mali'), np.str_('MOMDAN'), np.str_('GOSWAMI'), np.str_('BISHNOI'), np.str_('JAAT'), np.str_('HARIJAN'), np.str_('muslim'), np.str_('RAJPUT'), np.str_('ARORA'), np.str_('muslim'), np.str_('MAHAJAN'), np.str_('musalman'), np.str_('JAIN'), np.str_('JAAT'), np.str_('MOMDAN'), np.str_('MUSLMAN'), np.str_('RAJPOOT'), np.str_('RAYSIKH'), np.str_('BAIRWA'), np.str_('muslim'), np.str_('MAHAJAN'), np.str_('RAJPUT'), np.str_('MUSALMAN'), np.str_('HARIJAN'), np.str_('MUSLIM'), np.str_('SHARMA'), np.str_('Muslman'), np.str_('JAT SIKH'), np.str_('musalman'), np.str_('RAWAT'), np.str_('RAJPOOT'), np.str_('DESWALI MUSALMAN'), np.str_('VALMIKI'), np.str_('MUSLMAN'), np.str_('JATSIKH'), np.str_('Unknown'), np.str_('MUSLMAN'), np.str_('MUSALMAN'), np.str_('MUSALMAN'), np.str_('RAJPUT'), np.str_('SONI'), np.str_('JAIN'), np.str_('JAT'), np.str_('musalman'), np.str_('sargara'), np.str_('SWAMI'), np.str_('RAJPUT'), np.str_('NAYAK'), np.str_('RAYSIKH'), np.str_('MUSALMAN'), np.str_('MUSALMAN'), np.str_('KHATIK'), np.str_('ARORA'), np.str_('MUSALMAN'), np.str_('PATHAN MUSALMAN'), np.str_('musalman'), np.str_('MUSLMAN'), np.str_('JAAT'), np.str_('SHARMA'), np.str_('RAYSIKH'), np.str_('KHATIK'), np.str_('MUSALMAN'), np.str_('musalman'), np.str_('MUSLIM'), np.str_('PATHAN MUSALMAN'), np.str_('RAJPOOT'), np.str_('JAIN'), np.str_('Unknown'), np.str_('MOMDAN'), np.str_('Musalman'), np.str_('MUSLIM'), np.str_('MUSLMAN'), np.str_('PATHAN MUSALMAN'), np.str_('MUSLIM'), np.str_('PATHAN MUSALMAN'), np.str_('MUSLIM'), np.str_('muslim'), np.str_('MUSLIM'), np.str_('muslim'), np.str_('ARORA'), np.str_('BRAHMAN'), np.str_('BRAHMAN'), np.str_('NAYAK'), np.str_('Bishnoi'), np.str_('SONI'), np.str_('BAIRWA'), np.str_('ARORA'), np.str_('MALI'), np.str_('mali'), np.str_('MALI'), np.str_('BRAHMAN'), np.str_('DAROGA'), np.str_('BAIRWA'), np.str_('SONI'), np.str_('BAIRWA'), np.str_('BRAHMAN'), np.str_('BRAHMAN'), np.str_('SONI'), np.str_('muslim'), np.str_('muslim'), np.str_('MUSALMAN'), np.str_('AHIR'), np.str_('BRAHMAN'), np.str_('ARODA'), np.str_('BRAHAMAN'), np.str_('BAIRWA'

In [13]:

def tokenize(examples):
    return tokenizer(
        examples["Name"],
        padding="max_length",   # or padding=True for dynamic padding
        truncation=True
    )

test_dataset = dataset["test"].map(tokenize, batched=True)
pred_results = trainer.predict(test_dataset)
pred_labels = np.argmax(pred_results.predictions, axis=-1)
pred_categories = [le_caste.classes_[i] for i in pred_labels]
dict2["Caste"] = pred_categories
print(dict2['Name'])
print(dict2['Caste'])

Map:   0%|          | 0/666 [00:00<?, ? examples/s]

['ABHAY', 'PANCHAL MANOJ ', 'GONSALVES SUNNY', 'AMRIT', 'BAISOYA RISHABH', 'GIRI HEMANT', 'KADIAN YOGESH', 'SINGH HARBHEJ', 'SINGH JOGA', 'SHARMA SACHIN', 'BAJAJ RITIK', 'SINGH BARJINDER', 'KUMAR ANIL', 'PATEL PRITESH MUKESHBHAI', 'JAIN HARSHIT BABULAL', 'SINGH VIKRAMJEET', 'SANGWAN KAPIL', 'SINGH SATINDERJEET', 'SANDHU HARWINDER SINGH', 'SINGH RANDEEP', 'KOLANJA MOHAMMAD RAFEEQ', 'PURUSHAN SUDHEESH KUMAR', 'HAIDER SYED MUHAMMAD ARSHIYAN', 'NANAVATI ADITYA', 'SINGH GURJINDER', 'GUPTA VIKASH', 'SANDHU SHAMINDER SINGH', 'RAIJADA KAVALJITSINH MAHENDRASINH', 'SINGH HARSAHIB', 'ANGOM SANATOMBA SINGH', 'PUKHRAMBAM SAMANANDA SINGH', 'KSHETRIMAYUM BROJEN SINGH', 'TAKHELAMBAM RAGHU', 'THOKCHOM GANDHI SINGH', 'SULTAN AYAZ MOHAMMED', 'ARMAR MOHAMMAD SHAFI', 'SINGH KARANVIR', 'SINGH AVTAR', 'SINGH HARMEET', 'RANPARIYA JAYSUKH', 'SINGH JANG BAHADUR', 'SINGH GURMIT', 'BHANSALI MIHIR RASHMI', 'SINGH GURPREET', 'SINGH MEHENGA', 'LAMKANG STARSON', 'MOIRANGTHEM TAMBA', 'KHURAIJAM MAIPAK', 'MUNSHI SHAIKH ZAHIDMIYA', 'CHERIYA VEETTIL SADIQUE', 'GOTTIPARTHI SRINIVAS', 'AHMED SADAB', 'SHEIKH ABU RASID', 'HUSSAIN ANWAR', 'RAJBHAR BALARAM', 'ISHAQI SALIM', 'MOHD KHALID', 'BEG MIRZA SHADAAB', 'ALAM DR. SHAHNAWAZ', 'ARMAR ABDUL KHADER SULTAN', 'NEHRA AJAY', 'SINGH DEVESH KUMAR', 'IQBAL L IWANTHABA', 'PATIL RUDRA', 'LIMKAR PRAVEEN', 'CHOUDHARY MOHSIN', 'KAGZI FAYAZ', 'T R CALVIN RAINGAM', 'BAINS AMANDEEP SINGH', 'SHAHABANDRI RIYAZ AHAMED', 'SHAIKH HASSAN LUKMAN', 'JAMATIA COMREDPADA', 'JOSEPH THARAKAN PARRAYIL GEORGE', 'KHAN MOHAMMED SHOEB', 'DOLA SALIM', 'SINGH AMRIK', 'SINGH GURTEJ', 'AHMED FAHIM', 'PATEL BHARATBHAI VIHABHAI', 'MODI NIRAV DEEPAK', 'SINGH RAJ', 'CHAUHAN RAM', 'TAMANG JAIY', 'THOUDAM SOMORENDRO SINGH', 'BHUTHAM GOVINDU', 'MALBARI ABDUL RASHEED HUSAIN SHEIK', 'SHETTY BALAKRISHNA', 'BHAT ZAFFAR HUSSAIN', 'SHERA UMAR FAROOQ', 'DAR NAZIR AHMAD', 'NAG ARUP', 'GOSAIN PRAMOD', 'BABU NURBASHA MOHAMMAD', 'MOHAMMED ABU SAAD', 'DEEPAK RANJAN', 'YOGISH', 'DIAS CLEMANT VICTOR', 'KUMAR SAJJAN', 'PATIDAR RAMCHANDRA KALSANGARA', 'DANGE SANDEEP VASUDEV', 'DEBBARMA BUDHRAI', 'SAYYED MUZAKKIR MUDDASSAR HUSAIN', 'GURSHARAN SINGH KALER', 'CHOUDHARY SANJAY KUMAR', 'PATEL RAFIQ', 'VIJAY SHYAM SHETTY', 'BHATKAL IQBAL', 'BHALLA RAKESH MOHAN', 'SREEDHARAN SUDHIN KUMAR', 'MARQUES INACIO', 'DEVDIWALA FAROOQ', 'SINGH RAVI PRAKASH', 'SINGH BHAGWANT', 'CHAURASIYA BRIJ BHUSHAN', 'DAWREY RIZWAN MOHAMMAD', 'SEKAR', 'AMARJIT SINGH AMBA', 'SHARIFKHAN PATHAN', 'DEBBARMA SACHINDRA', 'FAROOQUI ABDUL ARIF', 'SHARMA SURESH', 'CHOUGULE IRFAN', 'CHANDOK SURENDER SINGH', 'SHEIK DAWOOD SHAHUL HAMEED', 'KSHETRIMAYUM NOYON SINGH', 'NAMOIJAM OKENDRO SINGH', 'SUMI NIKI', 'BANGARD NAVAL KISHORE', 'SIDDIQ ABUBAKKAR', 'SUKHMINDER SINGH BAINS BHOLA', 'DEEPAK MANIKAN', 'KHAN GULAM NABI', 'DAR MANZOOR AHMAD', 'MAQBOOL PANDIT MOHD', 'NARENGBAM MARIJIT SINGH', 'VENKATA PRAVEEN KUMAR RAJULAPATI', 'NICOL TAMANG', 'JAGDISHBHAI PUNJIRAM', 'GHORI MOHAMMED FARHATULLAH', 'PATEL NATUBHAI SATABHAI', 'PATEL DILIPBHAI BABUBHAI', 'BATRA DAMINDER SINGH', 'SHANKARAN RAVI', 'BANGER JASWINDER SINGH', 'SYED ALMAS MAHARAJ', 'HANIF TIGER', 'AGRAWAL SURENDRA', 'GADGIL NANDAN PRABHAKAR', 'BARUAH PARESH', 'SHAIKH SHAKEEL', 'SHAIKH ANIS', 'KASKAR DAWOOD IBRAHIM', 'SIVARAMA KURUP SUKUMARAN', 'VISHWANATHA SHETTY', 'SINGH GURUDEV', 'PREM SETHI', 'ANSARI TAHER', 'MOHD YUSUF SHAH', 'SAYED ARIF', 'DOSA MOHAMED AHMED', 'BEDI SURENDER SINGH', 'CHANDOK HARLEEN KAUR', 'NAUSHA KADEEJATH', 'STANLY VARGHESE BHUVANESWARI', 'EDADAN OMANA', 'ABDUL ASIF ABDUL SADIK', 'ABDUL GAFFAR ABDUL KADAR', 'ABDUL KHAN AYUB KHAN', 'Abdul Rafique Abdul Kabir', 'ABDUL SAJID ABDUL SAMAR', 'ABDUL SALIM ALIAS BADSHAHA ABDUL SALAM', 'ABDUL SHAKIR ALIAS ABDUL RAZAK', 'ABDUL WAJID ABDUL KHALID', 'ABDUL WASIM ABDUL SALAM', 'ABHISHEK VIVEK DESHMUKH', 'AJAY ARUN JUNGHARE', 'AJAY PRAKASH DABHADE', 'AKASH HARIBHAU PARTEKI', 'Akash Ramesh Wankhade', 'AKHILESH JAYANTILAL AADTIYA', 'Akshay Alias Shirish Shivdatta Mate', 'AKSHAY SURESH CHARHATE', 'AMAR ARVIND BONDE', 'AMAR BHARAT WAWER', 'AMIT RAMNARAYAN TIWARI', 'AMOL BABURAO DANGE', 'AMOL BAPURAO DANGE', 'AMOL DAYANAND WASNIK', 'AMOL DYANESHWAR RAUT', 'ANIL BHAGWATRAO MOHANKAR', 'ANIL DASHRATH KHADSE', 'ANIL RAMRAO WANKHADE', 'ANKUSH WASUDEV THAKARE', 'ANSAR KHAN ALIAS TANTYA YUSUF KHAN', 'Ansar Khan Mahommad Khan', 'ARSHID KHAN RASHID KHAN', 'ARUN RAMDAS YEDATKAR', 'ASHISH BABAN DESHMUKH', 'ASHOK ALIAS CHOTU SAHDEVRAO INGALE', 'ASHOK SHYAMA BHOSALE', 'ASHWIN ASHOK WANKHADE', 'ATAULLAH KHAN BISMILLA KHAN', 'ATUL MURALIDHAR NAIK', 'AVINASH ASHOK BHUYAR', 'AZAHAR BEIG KADAR BEIG', 'BABARAO DADARAO HIVRALE', 'BABLU KHAN HASIL KHAN', 'BADSHAH AJABSING TANK', 'BADSHAHASINGH AJABSINGH TANK', 'BADSHAHASINGH AJABSINGH TANK', 'BALU GULAB MAHALLE', 'BANDYA KISAN KALE', 'BARAKYA ALIAS HANSRAJ PAWAR', 'BARKYA ALIAS RAJHANS JARTARI PAWAR', 'BATKYA JALTARI PAWAR', 'BHARAT MOHAN DIVATE', 'BHOLU ALIAS SHAKIRNUR MOHAMMAD', 'BHOLU MORE', 'BHURE KHAN RAFIQUE KHAN NOOR KHAN', 'Bhushan Pradip Baseriya', 'BUNTY ALIAS RAVI SHYAM ATHIYA', 'BUNTY SHOKRAO PAWAR', 'CHARAN MANIK LADE', 'DADARAO HIRAMAN RANGARI', 'DADASING ALIAS RAJASING AJABSING TANK', 'DARASING KISAN MALAVE', 'DEELIP KISANRAO WAGH', 'DEELIP RAM KORDE', 'DEELIP SHIVACHAND CHUDIWALA', 'DEEPAK MADAN PATIL', 'DHANRAJ RAMASWAMI ZIRPILLAI', 'DILBARSING JOHANSING TANK', 'DILDAR KHAN SATTAR KHAN', 'DILIP KISAN PUNASE', 'DINESH NAMDEV KHEDKAR', 'DINESH NAWANDAR', 'DIPAK ALIAS NAKTYA GENDALAL GUPTA', 'DIPAK SHRIRAM KALE', 'DIWAKAR GOWARDHAN KHADSE', 'DYANESHWAR VITTHAL KALANE', 'FATTUSINGH INDRASINGH MILL', 'FIRDAUS KHAN MEHABUB KHAN', 'GAFFARALI SATTARALI', 'GAJANAN ARUN ATRAM', 'GAJANAN CHALISA BHOSALE', 'GAJANAN DADARAO NEWARE', 'GAJANAN GOPALRAO INGOLE', 'GAJANAN HIMMATRAO KARALE', 'GAJANAN PRALHAD KALPANDE', 'GANESH BABARAO PURI', 'GAURAV GAJANAN KAMBE', 'GAUTAM MOTIRAM GHODESWAR', 'Golu Alias Swapnil Mukund Shinde', 'GOPAL BABAN SOLANKE', 'GOPAL MADHUKAR THORAT', 'GOPAL MADHUKAR THORAT', 'GOVIND NARAYAN SAHU', 'GUDDU ALIAS SHEIKH ANSAR SHEIKH SATTAR', 'GULAM HASAN AULAD HUSAIN', 'HARIKESH ALIAS GUDDU MADAN KATTILWAR', 'HARSHAL ALIAS BALA MURLIDHAR GAWALE', 'HEMRAJ BHALALIYA SASI', 'IMRAN KHAN ALIAS BABLU ARIF KHAN', 'IRFAN KHAN SHARIF KHAN', 'IRFAN KHAN SHARIQUE KHAN', 'IRFANUDDIN GULFARAZUDDIN', 'JACKY ALIAS JAYKISAN RUPRAO PARADE', 'JANARDHAN ALIAS JANYA ALIAS JOHNY RAMRAO WAGHMARE ALIAS RAJESH SAANE', 'JARNAILSINGH ALIAS RAHULSINGH JYOGENDRASINGH TANK', 'JAY VIJAYKUMAR SHARMA', 'JAYANDRA PRAKASH KALE', 'JAYANT PRAKASH KALE', 'JAYPRAKASH NANDLAL MARIYA', 'JITENDRA AJAY DHOKE', 'JITU ALIAS JITENDRA RAMRAO BHAGAT', 'JYOTISINGH UMRAOSINGH BABARI', 'Kailash Kuwarsingh Bheel', 'KAILASH RATANSING PAWAR', 'KALYA ALIAS RAKESH MANJU BABA TAMBOLE', 'KARAN CHOKHELAL SEN', 'KISAN SHESHRAO HANDE', 'KULDEEPSINGH DARSHANSINGH JUNNI', 'LAL ALIAS HAFIZ SHAH HABIB SHAH', 'LAXAM AMBADAS SOLANKE', 'LAXMI VIRANNA ZHIRPILLAI', 'LOKESH JARTARI PAWAR', 'MAHADEV BHIMRAO GHORMADE', 'MAHESH ALIAS AJAY RAJKAMAL SASI', 'MAHESH CHAUBITRAM JIVTANI', 'MAISUR TABJUL BEIG SAFJALUL BEIG', 'MANGA VIRANNA ZIRPILALU', 'MANGESH ALIAS KALOTYA DEELIP WAGHMARE', 'MANGESH RAMDAS MUNDANE', 'MANGESH TULSHIRAM RAUT', 'MANISH ALIAS BABLU KESHAV NAGPURE', 'MANISH ROSHANLAL PUROHIT', 'MANOJ BABULAL SOLANKE', 'MANOJ LAXMAN GONDANE', 'MEHAMUD SHAH MUSTAFA SHAH', 'MEHBUB KHAN HAYAT KHAN', 'MOHABBATSINGH KAURSINGH THAKUR', 'MOHAMAD IMRAN MOINUDDIN', 'MOHAMAD JAMIL ALI NUSARAT ALI', 'MOHAMAD VASIM ISMAIL', 'MOHAMMAD JAWED MOHAMMAD MIRZA', 'MOHAMMADSINGH PARVATSINGH', 'MOHSEEN KHAN HAMID KHAN', 'MOMIN KHAN RAHEMAT KHAN', 'MUKESH LAKSHAMSINGH THAKUR', 'MUKUND DURYODHAN WAWARE', 'NAGESH NAMDEV KHEDKAR', 'NAJAKAT ALIAS NAJJA SHEIKH BABA', 'NARAYAN ALIAS ARYAN KALURAM DEVKAR', 'NARAYAN KISAN PATAKE', 'NARENDRA PRAKASH DHAGE', 'NARESH PADMAKAR NANDESHWAR', 'NASIN KHAN ALIAS NAJJA RASHID KHAN', 'NIJAMUDDIN AJIJ KHAN', 'NIKHIL VIJAY TIKALE', 'NILESH DEELIP POTFODE', 'NILESH HARIVIJAY UGHADE', 'NILESH TUKARAM CHAVHATE', 'NITIN MADHUKAR MESHRAM', 'NITIN MAROTRAO NALHE', 'NITIN NARESH CHAVHAN', 'NITU NATTHU DAWANDE', 'OM MADAN CHAUDHARI', 'OMPRAKASH BHARAT BHATAKAR', 'PANJAB UTTAMRAO GAJBHIYE', 'PANKAJ ALIAS DEBU AVADHUT GAJBHIYE', 'PANKAJ GANESH BHURAI', 'PANKAJ RAJU GONDANE', 'PANKAJ RAMDAS DHOKE', 'PANKAJ SURESH TAYADE', 'PAVAN ALIAS BHOLU SHANKAR BARAD', 'PAVAN ANIL TIDAKE', 'PAVAN DINKAR GALE', 'PAVAN PRAKASHCHANDRA MATWANI', 'PAVAN RAMESH TOPALE', 'PINTYA KISAN BHANDE', 'PRABHAKAR NAGORAO BHOWALE', 'PRADIP PANDURANG SHENDE', 'PRAKASH ALIAS ANTHONY ALIAS THOMAS DHANDAR', 'PRAKASH CHANDRBHAN BENDRE', 'PRAKASH DINESH ATHAVALE', 'PRAKASH JIYALDAS MANWANI', 'PRALHAD DHNYANESHWAR GAYAKWAD', 'PRAMOD DEVRAO BANSOD', 'PRAMOD MAHADEV DHANADE', 'PRAMOD UTTAM DHOKE', 'PRATIK DHANRAJ ZADE', 'PRATIK NAMDEO SHINDE', 'PRAVIN ALIAS PINTYA BHIMYA BANSOD', 'PRAVIN TULSHIRAM KADU', 'PRITAM PANDURANG SURWANSHI', 'PRUTHVI ASHOK WANKHADE', 'RAHAMAT KHAN BISMILLA KHAN', 'RAHUL AMBADAS GETHE', 'RAHUL AMBADAS GETHE', 'RAHUL SUDHAKAR KHOBRAGADE', 'RAJABHAU BOBADE', 'RAJESH BABULAL SOLANKE', 'RAJESH NARAYAN BITAKARI', 'RAJU DATTOPANT ATHAVALE', 'RAJU HOTCHAND ADWANI', 'RAJU SHARAD KALE', 'Rakesh Gopal Gehalod', 'RAMJAN SHAHA TUKDU SHAHA', 'RANU ALIAS RANDEEP CHAINSUKH CHANGANI', 'RASHID KHAN ALIAS MUNGUS GAUSADAR KHAN', 'RAVI ALIAS MAMA LALLUN KHURKHURIYA', 'RAVI CHARAN PATIL', 'RAVI NARAYAN KHADASE', 'RAVINDRA ALIAS GOND SHIVDAS DHOKE', 'RAVINDRA HARIDAS PANEKAR', 'REHANA BANO AHAMAD SHAH', 'Rohit Ganeshrao Ajabe', 'ROSHAN DHASAKAT', 'ROSHAN SANJAY DESHMUKH', 'ROSHAN SURESH KHOBRAGADE', 'ROSHAN VINAYAK ROHANKAR', 'ROSHAN WASUDEV DHASKAT', 'RUPESH BANGADE', 'RUSHIKESH TULSHIRAM KANTALE', 'SACHIN BHASKAR LANJEWAR', 'SACHIN DINKAR CHAUDHARI', 'SACHIN SHRIKRUSHNA DESHMUKH', 'SACHIN WALKHADE', 'SAFDAR BEIG AZAGAR BEIG', 'SAGAR JANARDHAN GOGATE', 'SAGAR JANRAO WANKHADE', 'SAGAR NANAJI WANKHADE', 'SAGAR NARAYAN KHANDARE', 'SAGARSING MAYASING TANK', 'SAIF AHAMAD FARUK AHAMAD', 'SAIYAD ASIF SAIYAD BHURU', 'SAIYAD NIYAJ SAIYAD MUZHAFAR', 'SAIYAD SHAFIQUE SAIYAD RAFIQUE', 'SAIYAD SHAKIR SAIYAD BHURA', 'SALEM DASU GOGALU', 'SALIM KHAN ALIAS SALLU RAFIQUE KHAN', 'SAMAD SHAUKAT SAMAD ABDUL', 'SANDIP DADARAO PAHADAN', 'SANDIP KISAN VAIDYA', 'SANDIP RAMESH RAUT', 'SANDIP SHANKAR KSHIRSAGAR', 'SANGAM HANUMANT MESHRAM', 'SANGITA JADHAV', 'SANJAY ALIAS FANTER DHANSUKH BUDHWANI', 'SANJAY AMBADAS THOSARE', 'SANJAY DEELIP GHODE', 'SANJAY SHANKAR AWARE', 'SANTOSH BANSOD', 'SANTOSH KESHAV KINNAKE', 'SANTOSH SHALIKRAM GAYAKWAD', 'SATISH ALIAS GOLU PURUSHOTTAM SIDAM', 'SATISH ALIAS SATTYA UKADRAO KUROTIYA', 'SATISH BHAGATSINGH SOLANKE', 'SATTYA ALIAS SATISH UKANDRAO KUTORIYA', 'SHAKIR NUR MOHOMMAD KHAN', 'SHAMIULLA KHAN HAFIZULLA KHAN', 'SHAMMI SHAHA MURAD SHAHA', 'SHANKAR SUBHASH BANSOD', 'SHARIK ALI ASHAK ALI KHAN', 'SHASHIKANT PRABHUDAYAL UPADDHYAY', 'SHASHIKUMAR SAHEBRAO TATTE', 'SHEIKH ANSAR NIYAJ ALI', 'SHEIKH ARIF ALIAS GUDDU SHEIKH YUSUF', 'SHEIKH ARIF SHEIKH MUSUD', 'SHEIKH ASIF SHEIKH GUDDU', 'SHEIKH AYUB SHEIKH IBRAHIM', 'SHEIKH CHAND SHEIKH BHURU', 'SHEIKH CHHOTU ARIF SHEIKH DILAWAR', 'SHEIKH CHOTU SHEIKH DILAWAR', 'SHEIKH FIROZ SHEIKH YAKUB', 'SHEIKH GOLU SHEIKH BABA', 'SHEIKH GOLU SHEIKH KADAR', 'SHEIKH HAMID ALIAS MOTU SHEIKH HANIF', 'SHEIKH HAMID ALIAS MOTU SHEIKH HANIF', 'SHEIKH HASAN SHEIKH HUSAIN', 'SHEIKH IRAFAN SHEIKH BISMILLAH', 'SHEIKH JAFAR SHEIKH KARIM', 'SHEIKH JAVED SHEIKH BHURU', 'SHEIKH JAWED ALIAS DADU SHEIKH SABIR', 'SHEIKH JAWED SHEIKH BHURU', 'SHEIKH MATIN SHEIKH MEHABUB', 'SHEIKH RAFIQUE NABIULLA SHEIKH ALIAS SHEKHAR PATIL', 'SHEIKH RIZWAN ALIAS MUNNA MOBILE SHEIKH JALIL', 'SHEIKH SABIR SHEIKH IMAM', 'Sheikh Salman Sheikh Shakur', 'Sheikh Shahid Sheikh Chand', 'SHEIKH TOUFIQUE SHEIKH RAFIQUE', 'SHIVA ALIAS SHIVAJI VITTHAL BHOSALE ALIAS BHOLE', 'SHOBI ALIAS SHOHEB BABBU SARPANCH', 'SHRIKRUSHANA PINTYA DEVIDAS GAHUKAR', 'SHUBHAM GAJANAN SAYANKE', 'SHYAM GAJANAN PURI', 'SHYAM MADAN PATHAK', 'SINNA CHINNA ATAPALLI', 'SONYA ALIAS MANGESH BHIMRAO CHANDURKAR', 'SUBODH BHIMARAO DHAKADE', 'SUDHIR DADARAO PUND', 'SUDHIR LAXMAN JAVANJAL', 'SUDHIR SURESH LAHUPANCHANG', 'SUHAS ALIAS PRAKASH ASHOK JOSHI', 'SUNIL JAYDEV MESHRAM', 'SUNIL PRAKASH GULSUNDARE', 'SUNIL SHANKARRAO MATE', 'SUNIL SHYAMRAO UKE', 'SUNNY SUNIL BIJAVE', 'SURAJ GAJANAN DESHKAR', 'SURAJ PURUSHOTTAM GUPTA', 'SURENDRA RAOSAHEB KORE', 'SURENDRA UDHAVRAO WAKODE', 'SURESH PRAKASH RANGARI', 'SURESH SUDHAKAR GANDHE', 'SUSHANT ARUN GANJARE', 'SUSHIL ALIAS KHANDYA WANKHADE', 'SUYASH CHANDRASHEKHAR DORLE', 'SWAPNIL MOTIRAM MESHRAM', 'Swapnil Vinay Bangre', 'TAANYA ALIAS TANAJI VITTHAL BHOSALE', 'TIRUMALLI WALKISAN ATAPALLI', 'UJWAL ALIAS SONU SHEKHAR KAMKARE', 'UMESH BHUJANGRAO MAHALLE', 'VASIM KHAN YUSUF KHAN', 'VIJAY NAJUK INGALE', 'Vijay Pandurang Raybole', 'VIJAY SANJAY SURYAWANSHI', 'VIJAY TULASHIRAM KALE', 'VIKAS RAMJI CHAPALKAR', 'VIKKY ALIAS ASHOK GANOSKAR', 'VIKKY DHANARAJ KHANDARE', 'VIKKY RAJENDRA GADLING', 'VINOD ARUN KOTHE', 'VIRANNA BANKKATAPPA ZIRPILALU', 'VISHAL ARUN PAWAR', 'VITTHAL SHANKARAO MANKAR', 'Vivek Alias Bikku Ravindra Pande', 'VIVEK ALIAS BODYA VINAYAK NIRMAL', 'WAHID KHAN SAID KHAN', 'WAMAN JAGAN NAIK', 'WASANT SHANKAR CHAUDHARI', 'YOGESH ALIAS LAKHAN RAMESH WANKHADE', 'YOGESH GOVIND TAYADE', 'YUSUF ALI ASHAF ALI KHAN', 'ZAHIR SHEKHU KHURSHID ABBAS', 'ZAKIR HUSAIN JINNATALI', 'RAJESH KUMAR', 'Shri Deepankar Barman', 'Shr Hasen Ali', 'Shri Mohibul Prodhani', 'Azirul Islam alias Aziul Hoque', 'Shri Sunil Gogoi', 'Shahabaj Jakaria Shikdar', 'Ferdynald Kharkamni', 'Shri Arun Kumar Jain', 'Shri Santanu Mizar', 'Shri Amit Paul', 'Shri Lakstar Khariap', 'Shri Pujam Gurung', 'Shri Tilok Dorjee', 'Shri Mukhiya Singh', 'Shri Jhuggo Jasoda', 'Shri Shanborlang Rani alias Dengdeng', 'Shri Rohit', 'Bringo Lyngdoh', 'Nayan Bhattacharjee', 'Shri Sandeep Sunar', 'Shri Din Dayal Sharma', 'Shri Harlal Jat', 'Shri Majidul Khan', 'Shri Dilip Baspor', 'Shri Eyahia Ahmed', 'Shri Biswajit Yadav', 'Shri Amit Ghosh', 'Shri Mithun Sharma', 'Shri Nihar Ranjan Bhattachariya ', 'Shri Santosh Hajong ', 'Smti Balarisa Nengnong', 'Shri Diganta Kumar Adhikari', 'Shri Dilip Kumar', 'Shri Arjun Burman', 'SHRI DANIEL HAWK ', 'Shri Ramesh Gurung ', 'Smti Anandi Chapagai', 'Shri Khimananda Chapagai', 'Biswng Prasad Chattri', 'Shri Tapan Ojha', 'Shri Manseng D Sangma', 'Shri Lalit Dey', 'Shri Nur Mohmmed', 'Shri Asraful Ali', 'Shri Babeshor Kalandi', 'Shri Rex Briller R Marak', 'Miss Eunice Zimik', 'Shri Prema', 'Shri Shynsharlang Thongni', 'Shri Sumon Namo ', 'Smti Jesica Kharkongor ', 'Shri Mukesh Sangma', 'Bhim Singh', 'Shri Konesshon Rodborn ', 'Shri Thoudam Prasanta Singh  ', 'Chatu', 'Madhurendra Singh', 'Rousan', 'Bablu Rewani', 'Sunil Madni', 'Tribeni Prasad', 'Guljar Ansari', 'Samim', 'Kishore Mondal', 'Sakir Ansari', 'MD. SIRAJ', 'MD. NAUSHAD KHAN', 'MD. AKTAR KHAN', 'AKBAR KHAN', 'PABAN KUMAR YADAV', 'AMIT KUMAR YADAV', 'KALIYA KURMI', 'PINTU DEY', 'DHARMENDRA', 'UJJAL BOURI', 'MD NAWSAD', 'CASHIER', 'SK. LAL', 'RAKESH HELA', 'RAJESH VERMA', 'NANDA BOURI', 'KRISHNA DAS', 'KARA RAJ BANGSI', 'KRISHNA YADAV', 'BAIJU PRASAD RAM', 'LOKE NATH MUKHERJEE', 'SUBRATA SARKAR', 'PRITAM DAS', 'RANJIT HELA', 'RAJU RUIDAS', 'RAJU BOURI', 'RAHUL YADAV', 'PINTU RUIDAS', 'LAXMAN LAMA', 'LACHMI SAHANI', 'KARKAT DAS', 'JOGI DAS', 'GOUR SENGUPTA', 'BHALTU PASI', 'BESAN RUIDAS', 'BALDEV TURI', 'AUSTA RUIDAS', 'ANAND PASWAN', 'TIPU ANSARI', 'SUSHIL RAM', 'SURAJIT SARKAR', 'SK TAHIR', 'SK  SAMSOL', 'SK MOHIBUL', 'SK KHALID', 'SK IMAMUL', 'SK ILIAS', 'SK ASHRAF', 'SK AKHTAR', 'SK ABAR ALI', 'SARUDDIN', 'PRADIP KR TIWARI', 'MRINAL KANTI GHOSH', 'MOHAN RUIDAS', 'MD SHANAWAR', 'MD RIZWAN', 'MD NOUSAD', 'MD-IMTIYAJ', 'MANOJ-DOM', 'UTPAL-GHOSH', 'JITEN-PAUL', 'BADYANATH MONDAL', 'BURO BOURI', 'BIRJU PASWAN', 'SANJOY KR SUKLA', 'Mithilesh Kumar Singh', 'Khusbu', 'Rajesh Paswan', 'Manoj Mallick', 'Amar Mahato', 'MOHAN', 'Kanahi Bouri', 'Nimai Ruidas', 'Sanjoy Ruidas', 'Santosh Rewani', 'Sushil', 'Srimanta Ruidas', 'Manik Das', 'Rahul', 'RAJU', 'Gour', 'Raju Bauri', 'Besan', 'Bhaltu', 'Kartak Das', 'Jogi', 'Lachmi', 'Anand Paswan', 'Austa', 'Astik', 'BALDV TURI', 'LAXMAN']

In [16]:
print(cluster1)

['sc/st', 'unknown', 'unknown', 'unknown', 'obc', 'unknown', 'unknown', 'muslim', 'muslim', 'muslim', 'sc/st', 'obc', 'obc', 'obc', 'muslim', 'obc', 'obc', 'sc/st', 'sc/st', 'general', 'obc', 'obc', 'muslim', 'general', 'obc', 'general', 'obc', 'sc/st', 'muslim', 'obc', 'unknown', 'obc', 'muslim', 'general', 'sc/st', 'muslim', 'obc', 'muslim', 'sc/st', 'unknown', 'sc/st', 'unknown', 'sc/st', 'sc/st', 'obc', 'general', 'unknown', 'general', 'sc/st', 'obc', 'general', 'obc', 'muslim', 'obc', 'muslim', 'obc', 'muslim', 'general', 'unknown', 'unknown', 'obc', 'general', 'sc/st', 'muslim', 'muslim', 'general', 'obc', 'unknown', 'unknown', 'muslim', 'sc/st', 'general', 'obc', 'general', 'obc', 'sc/st', 'sc/st', 'general', 'sc/st', 'general', 'obc', 'sc/st', 'obc', 'obc', 'general', 'obc', 'obc', 'general', 'sc/st', 'sc/st', 'unknown', 'sc/st', 'unknown', 'obc', 'obc', 'unknown', 'obc', 'obc', 'obc', 'obc', 'muslim', 'unknown', 'unknown', 'unknown', 'obc', 'muslim', 'sc/st', 'muslim', 'obc', 'sc/st', 'sc/st', 'general', 'muslim', 'unknown', 'unknown', 'obc', 'sc/st', 'general', 'obc', 'unknown', 'obc', 'muslim', 'sc/st', 'sc/st', 'unknown', 'obc', 'obc', 'muslim', 'muslim', 'unknown', 'sc/st', 'unknown', 'sc/st', 'general', 'unknown', 'muslim', 'unknown', 'muslim', 'unknown', 'unknown', 'unknown', 'obc', 'sc/st', 'sc/st', 'obc', 'unknown', 'unknown', 'obc', 'sc/st', 'obc', 'muslim', 'sc/st', 'obc', 'muslim', 'obc', 'general', 'unknown', 'unknown', 'unknown', 'sc/st', 'unknown', 'sc/st', 'muslim', 'unknown', 'general', 'obc', 'general', 'muslim', 'general', 'muslim', 'general', 'obc', 'general', 'sc/st', 'general', 'unknown', 'sc/st', 'unknown', 'sc/st', 'obc', 'sc/st', 'muslim', 'unknown', 'sc/st', 'muslim', 'unknown', 'general', 'muslim', 'muslim', 'unknown', 'obc', 'general', 'obc', 'muslim', 'obc', 'muslim', 'obc', 'muslim', 'muslim', 'unknown', 'muslim', 'unknown', 'sc/st', 'obc', 'sc/st', 'muslim', 'sc/st', 'obc', 'sc/st', 'obc', 'sc/st', 'sc/st', 'muslim', 'sc/st', 'sc/st', 'muslim', 'general', 'sc/st', 'obc', 'unknown', 'unknown', 'sc/st', 'general', 'unknown', 'obc', 'muslim', 'unknown', 'general', 'unknown', 'obc', 'sc/st', 'obc', 'unknown', 'obc', 'muslim', 'obc', 'obc', 'obc', 'general', 'general', 'obc', 'sc/st', 'general', 'muslim', 'obc', 'unknown', 'general', 'obc', 'general', 'obc', 'muslim', 'sc/st', 'obc', 'obc', 'unknown', 'unknown', 'general', 'obc', 'obc', 'unknown', 'sc/st', 'unknown', 'sc/st', 'unknown', 'sc/st', 'obc', 'sc/st', 'general', 'unknown', 'unknown', 'general', 'obc', 'unknown', 'muslim', 'sc/st', 'muslim', 'unknown', 'unknown', 'unknown', 'general', 'sc/st', 'muslim', 'sc/st', 'muslim', 'obc', 'sc/st', 'muslim', 'unknown', 'unknown', 'obc', 'general', 'obc', 'unknown', 'unknown', 'sc/st', 'sc/st', 'unknown', 'muslim', 'general', 'unknown', 'muslim', 'unknown', 'general', 'obc', 'unknown', 'general', 'muslim', 'obc', 'sc/st', 'unknown', 'general', 'sc/st', 'obc', 'unknown', 'general', 'obc', 'unknown', 'general', 'obc', 'unknown', 'general', 'general', 'obc', 'sc/st', 'sc/st', 'obc', 'muslim', 'obc', 'unknown', 'unknown', 'unknown', 'unknown', 'general', 'unknown', 'unknown', 'general', 'obc', 'obc', 'sc/st', 'sc/st', 'unknown', 'muslim', 'sc/st', 'unknown', 'obc', 'obc', 'sc/st', 'muslim', 'obc', 'obc', 'obc', 'muslim', 'sc/st', 'unknown', 'obc', 'sc/st', 'general', 'sc/st', 'muslim', 'obc', 'general', 'sc/st', 'sc/st', 'unknown', 'sc/st', 'general', 'sc/st', 'unknown', 'muslim', 'muslim', 'general', 'general', 'sc/st', 'unknown', 'sc/st', 'muslim', 'unknown', 'unknown', 'obc', 'unknown', 'unknown', 'unknown', 'sc/st', 'general', 'general', 'unknown', 'sc/st', 'muslim', 'general', 'unknown', 'sc/st', 'general', 'sc/st', 'sc/st', 'general', 'unknown', 'general', 'general', 'unknown', 'sc/st', 'sc/st', 'obc', 'sc/st', 'unknown', 'general', 'obc', 'sc/st', 'sc/st', 'general', 'unknown', 'general', 'unknown', 'obc', 'obc', 'obc', 'muslim', 'obc', 'obc', 'muslim', 'general', 'unknown', 'general', 'obc', 'obc', 'muslim', 'general', 'muslim', 'sc/st', 'obc', 'general', 'obc', 'obc', 'sc/st', 'unknown', 'obc', 'sc/st', 'sc/st', 'sc/st', 'unknown', 'unknown', 'general', 'general', 'obc', 'obc', 'general', 'obc', 'unknown', 'sc/st', 'unknown', 'sc/st', 'obc', 'unknown', 'obc', 'general', 'general', 'obc', 'unknown', 'general', 'general', 'general', 'obc', 'obc', 'unknown', 'unknown', 'sc/st', 'unknown', 'obc', 'obc', 'obc', 'obc', 'muslim', 'unknown', 'unknown', 'muslim', 'obc', 'sc/st', 'obc', 'unknown', 'general', 'general', 'muslim', 'obc', 'obc', 'sc/st', 'obc', 'obc', 'general', 'general', 'sc/st', 'unknown', 'obc', 'unknown', 'unknown', 'muslim', 'sc/st', 'unknown', 'muslim', 'obc', 'unknown', 'unknown', 'unknown', 'muslim', 'unknown', 'unknown', 'obc', 'sc/st', 'unknown', 'sc/st', 'unknown', 'unknown', 'sc/st', 'obc', 'unknown', 'sc/st', 'obc', 'muslim', 'unknown', 'unknown', 'muslim', 'general', 'obc', 'general', 'general', 'unknown', 'obc', 'general', 'obc', 'unknown', 'sc/st', 'sc/st', 'unknown', 'unknown', 'unknown', 'unknown', 'general', 'obc', 'sc/st', 'general', 'muslim', 'obc', 'sc/st', 'muslim', 'sc/st', 'general', 'obc', 'general', 'muslim', 'unknown', 'unknown', 'obc', 'muslim', 'unknown', 'obc', 'muslim', 'obc', 'obc', 'obc', 'general', 'obc', 'obc', 'muslim', 'sc/st', 'unknown', 'sc/st', 'unknown', 'obc', 'general', 'obc', 'obc', 'muslim', 'obc', 'unknown', 'unknown', 'unknown', 'sc/st', 'sc/st', 'general', 'sc/st', 'general', 'obc', 'muslim', 'general', 'general', 'sc/st', 'sc/st', 'muslim', 'general', 'sc/st', 'sc/st', 'muslim', 'sc/st', 'obc', 'unknown', 'unknown', 'muslim', 'unknown', 'obc', 'obc', 'general', 'general', 'general', 'unknown', 'obc', 'obc', 'obc', 'obc', 'muslim', 'sc/st', 'muslim', 'obc', 'unknown', 'obc', 'unknown', 'obc', 'muslim', 'obc', 'general', 'muslim', 'muslim', 'sc/st', 'obc', 'general', 'unknown', 'obc', 'sc/st', 'obc', 'general', 'general', 'sc/st', 'sc/st', 'general', 'unknown', 'muslim', 'sc/st', 'unknown', 'obc', 'muslim', 'unknown', 'general', 'unknown', 'obc', 'sc/st', 'sc/st', 'sc/st', 'general', 'general', 'sc/st', 'muslim', 'obc', 'unknown', 'obc', 'sc/st', 'sc/st', 'obc', 'unknown', 'obc', 'obc', 'obc', 'sc/st', 'sc/st', 'obc', 'unknown', 'muslim', 'sc/st', 'obc', 'sc/st', 'unknown', 'obc', 'obc', 'muslim', 'obc', 'general', 'muslim', 'unknown', 'unknown', 'unknown', 'obc', 'general', 'obc', 'obc', 'obc', 'obc', 'obc', 'unknown', 'muslim', 'obc', 'sc/st', 'general', 'sc/st', 'unknown', 'unknown', 'sc/st', 'unknown', 'sc/st', 'unknown', 'sc/st', 'sc/st', 'unknown', 'obc', 'unknown', 'muslim', 'general', 'obc', 'obc', 'sc/st', 'muslim', 'sc/st', 'obc', 'sc/st', 'general', 'sc/st', 'obc', 'muslim', 'general', 'unknown', 'general', 'obc', 'muslim', 'obc', 'unknown', 'unknown', 'unknown', 'obc', 'general', 'obc', 'muslim', 'unknown', 'obc', 'general', 'obc', 'unknown', 'muslim', 'sc/st', 'muslim', 'obc', 'unknown', 'obc', 'general', 'muslim', 'sc/st', 'obc', 'obc', 'muslim', 'muslim', 'obc', 'sc/st', 'unknown', 'general', 'muslim', 'unknown', 'unknown', 'sc/st', 'sc/st', 'general', 'sc/st', 'muslim', 'muslim', 'sc/st', 'obc', 'unknown', 'obc', 'obc', 'unknown', 'obc', 'general', 'unknown', 'sc/st', 'unknown', 'general', 'obc', 'sc/st', 'muslim', 'sc/st', 'unknown', 'muslim', 'sc/st', 'unknown', 'unknown', 'sc/st', 'muslim', 'obc', 'unknown', 'muslim', 'obc', 'obc', 'general', 'general', 'obc', 'obc', 'muslim', 'general', 'unknown', 'sc/st', 'unknown', 'general', 'unknown', 'unknown', 'muslim', 'unknown', 'obc', 'unknown', 'general', 'muslim', 'muslim', 'unknown', 'sc/st', 'obc', 'unknown', 'sc/st', 'obc', 'unknown', 'unknown', 'sc/st', 'muslim', 'unknown', 'obc', 'sc/st', 'sc/st', 'obc', 'sc/st', 'sc/st', 'unknown', 'obc', 'general', 'muslim', 'general', 'muslim', 'muslim', 'obc', 'muslim', 'general', 'general', 'obc', 'muslim', 'general', 'unknown', 'muslim', 'muslim', 'unknown', 'obc', 'general', 'general', 'obc', 'unknown', 'muslim', 'muslim', 'obc', 'obc', 'obc', 'unknown', 'general', 'obc', 'sc/st', 'unknown', 'muslim', 'sc/st', 'muslim', 'unknown', 'unknown', 'obc', 'general', 'unknown', 'sc/st', 'general', 'obc', 'sc/st', 'obc', 'unknown', 'muslim', 'sc/st', 'general', 'unknown', 'general', 'general', 'general', 'unknown', 'muslim', 'obc', 'unknown', 'obc', 'general', 'obc', 'unknown', 'sc/st', 'sc/st', 'unknown', 'muslim', 'muslim', 'unknown', 'unknown', 'muslim', 'sc/st', 'obc', 'obc', 'general', 'general', 'general', 'sc/st', 'muslim', 'unknown', 'sc/st', 'obc', 'general', 'sc/st', 'general', 'general', 'unknown', 'obc', 'obc', 'muslim', 'unknown', 'unknown', 'unknown', 'general', 'muslim', 'obc', 'obc', 'general', 'unknown', 'unknown', 'obc', 'unknown', 'obc', 'obc', 'general', 'general', 'general', 'obc', 'sc/st', 'general', 'unknown', 'general', 'muslim', 'sc/st', 'unknown', 'unknown', 'obc', 'sc/st', 'muslim', 'muslim', 'muslim', 'obc', 'obc', 'muslim', 'unknown', 'obc', 'obc', 'unknown', 'sc/st', 'unknown', 'unknown', 'sc/st', 'sc/st', 'muslim', 'sc/st', 'sc/st', 'unknown', 'unknown', 'sc/st', 'unknown', 'unknown', 'unknown', 'obc', 'muslim', 'unknown', 'obc', 'muslim', 'obc', 'obc', 'muslim', 'obc', 'unknown', 'obc', 'sc/st', 'obc', 'general', 'obc', 'obc', 'obc', 'general', 'obc', 'sc/st', 'muslim', 'muslim', 'unknown', 'obc', 'unknown', 'obc', 'sc/st', 'obc', 'sc/st', 'unknown', 'general', 'unknown', 'muslim', 'obc', 'sc/st', 'unknown', 'sc/st', 'muslim', 'unknown', 'obc', 'muslim', 'muslim', 'obc', 'muslim', 'muslim', 'muslim', 'general', 'obc', 'unknown', 'obc', 'obc', 'sc/st', 'sc/st', 'unknown', 'general', 'sc/st', 'muslim', 'unknown', 'unknown', 'general', 'general', 'sc/st', 'unknown', 'unknown', 'unknown', 'general', 'unknown', 'general', 'obc', 'obc', 'obc', 'general', 'unknown', 'sc/st', 'unknown', 'obc', 'obc', 'obc', 'unknown', 'sc/st', 'general', 'muslim', 'sc/st', 'muslim', 'general', 'obc', 'muslim', 'general', 'unknown', 'sc/st', 'general', 'obc', 'muslim', 'obc', 'muslim', 'general', 'general', 'muslim', 'unknown', 'muslim', 'muslim', 'sc/st', 'obc', 'obc', 'sc/st', 'unknown', 'obc', 'sc/st', 'unknown', 'obc', 'obc', 'unknown', 'general', 'muslim', 'unknown', 'unknown', 'unknown', 'obc', 'sc/st', 'obc', 'unknown', 'sc/st', 'sc/st', 'sc/st', 'general', 'obc', 'muslim', 'obc', 'unknown', 'obc', 'unknown', 'sc/st', 'unknown', 'general', 'obc', 'unknown', 'general', 'unknown', 'muslim', 'unknown', 'unknown', 'general', 'sc/st', 'obc', 'obc', 'general', 'obc', 'obc', 'general', 'muslim', 'sc/st', 'obc', 'obc', 'obc', 'sc/st', 'general', 'general', 'obc', 'unknown', 'unknown', 'unknown', 'general', 'sc/st', 'muslim', 'sc/st', 'muslim', 'general', 'obc', 'general', 'unknown', 'sc/st', 'general', 'muslim', 'general', 'sc/st', 'general', 'obc', 'unknown', 'sc/st', 'unknown', 'muslim', 'obc', 'unknown', 'muslim', 'obc', 'unknown', 'general', 'general', 'obc', 'unknown', 'sc/st', 'obc', 'unknown', 'sc/st', 'obc', 'obc', 'sc/st', 'general', 'obc', 'general', 'muslim', 'muslim', 'muslim', 'sc/st', 'obc', 'sc/st', 'muslim', 'obc', 'sc/st', 'obc', 'obc', 'muslim', 'general', 'obc', 'sc/st', 'unknown', 'sc/st', 'obc', 'unknown', 'obc', 'unknown', 'unknown', 'obc', 'sc/st', 'sc/st', 'obc', 'muslim', 'unknown', 'unknown', 'obc', 'unknown', 'unknown', 'general', 'unknown', 'sc/st', 'muslim', 'muslim', 'general', 'obc', 'general', 'muslim', 'unknown', 'obc', 'general', 'sc/st', 'general', 'general', 'general', 'unknown', 'muslim', 'unknown', 'muslim', 'sc/st', 'obc', 'muslim', 'unknown', 'obc', 'obc', 'sc/st', 'obc', 'general', 'obc', 'muslim', 'sc/st', 'sc/st', 'general', 'general', 'general', 'sc/st', 'obc', 'unknown', 'general', 'general', 'sc/st', 'muslim', 'general', 'muslim', 'sc/st', 'sc/st', 'sc/st', 'unknown', 'unknown', 'unknown', 'obc', 'general', 'unknown', 'sc/st', 'unknown', 'sc/st', 'unknown', 'muslim', 'obc', 'obc', 'unknown', 'obc', 'unknown', 'sc/st', 'muslim', 'obc', 'sc/st', 'obc', 'unknown', 'obc', 'obc', 'general', 'obc', 'muslim', 'muslim', 'sc/st', 'muslim', 'unknown', 'unknown', 'unknown', 'unknown', 'unknown', 'muslim', 'obc', 'sc/st', 'unknown', 'unknown', 'obc', 'general', 'obc', 'muslim', 'general', 'obc', 'obc', 'unknown', 'sc/st', 'obc', 'sc/st', 'muslim', 'general', 'obc', 'sc/st', 'unknown', 'general', 'obc', 'obc', 'general', 'obc', 'sc/st', 'obc', 'general', 'sc/st', 'obc', 'general', 'general', 'obc', 'obc', 'unknown', 'unknown', 'unknown', 'sc/st', 'muslim', 'muslim', 'obc', 'obc', 'obc', 'obc', 'unknown', 'muslim', 'obc', 'muslim', 'general', 'general', 'unknown', 'obc', 'obc', 'unknown', 'obc', 'muslim', 'general', 'sc/st', 'unknown', 'unknown', 'obc', 'obc', 'general', 'unknown', 'unknown', 'general', 'general', 'unknown', 'unknown', 'unknown', 'obc', 'muslim', 'obc', 'unknown', 'unknown', 'general', 'muslim', 'obc', 'obc', 'obc', 'sc/st', 'unknown', 'unknown', 'obc', 'obc', 'unknown', 'unknown', 'sc/st', 'muslim', 'obc', 'sc/st', 'sc/st', 'obc', 'unknown', 'unknown', 'obc', 'obc', 'muslim', 'unknown', 'unknown', 'unknown', 'unknown', 'general', 'obc', 'obc', 'sc/st', 'obc', 'sc/st', 'muslim', 'muslim', 'sc/st', 'muslim', 'unknown', 'muslim', 'unknown', 'sc/st', 'sc/st', 'unknown', 'unknown', 'muslim', 'general', 'unknown', 'unknown', 'unknown', 'obc', 'obc', 'unknown', 'unknown', 'general', 'obc', 'unknown', 'obc', 'muslim', 'obc', 'obc', 'unknown', 'obc', 'muslim', 'muslim', 'obc', 'unknown', 'obc', 'obc', 'obc', 'obc', 'obc', 'unknown', 'obc', 'sc/st', 'unknown', 'obc', 'obc', 'muslim', 'sc/st', 'unknown', 'general', 'unknown', 'unknown', 'sc/st', 'sc/st', 'sc/st', 'unknown', 'unknown', 'obc', 'muslim', 'obc', 'sc/st', 'muslim', 'unknown', 'unknown', 'unknown', 'unknown', 'unknown', 'muslim', 'general', 'obc', 'unknown', 'general', 'muslim', 'unknown', 'sc/st', 'muslim', 'unknown', 'obc', 'general', 'unknown', 'sc/st', 'unknown', 'obc', 'sc/st', 'general', 'obc', 'obc', 'obc', 'obc', 'obc', 'obc', 'general', 'sc/st', 'obc', 'sc/st', 'sc/st', 'muslim', 'unknown', 'obc', 'unknown', 'general', 'obc', 'obc', 'general', 'general', 'obc', 'unknown', 'obc', 'obc', 'unknown', 'sc/st', 'sc/st', 'sc/st', 'obc', 'muslim', 'unknown', 'muslim', 'general', 'obc', 'sc/st', 'general', 'sc/st', 'general', 'unknown', 'obc', 'obc', 'obc', 'general', 'obc', 'general', 'obc', 'muslim', 'obc', 'sc/st', 'obc', 'unknown', 'sc/st', 'obc', 'sc/st', 'sc/st', 'unknown', 'muslim', 'unknown', 'general', 'muslim', 'obc', 'unknown', 'obc', 'general', 'unknown', 'muslim', 'unknown', 'general', 'general', 'muslim', 'obc', 'obc', 'general', 'sc/st', 'general', 'obc', 'unknown', 'sc/st', 'general', 'unknown', 'obc', 'muslim', 'obc', 'sc/st', 'sc/st', 'general', 'muslim', 'muslim', 'muslim', 'obc', 'sc/st', 'general', 'general', 'unknown', 'unknown', 'unknown', 'unknown', 'sc/st', 'muslim', 'muslim', 'general', 'sc/st', 'muslim', 'general', 'sc/st', 'muslim', 'muslim', 'obc', 'obc', 'muslim', 'unknown', 'unknown', 'obc', 'general', 'unknown', 'general', 'unknown', 'unknown', 'obc', 'sc/st', 'obc', 'obc', 'obc', 'unknown', 'unknown', 'unknown', 'muslim', 'obc', 'muslim', 'obc', 'general', 'muslim', 'obc', 'general', 'unknown', 'unknown', 'muslim', 'obc', 'sc/st', 'muslim', 'unknown', 'muslim', 'unknown', 'general', 'sc/st', 'general', 'obc', 'unknown', 'muslim', 'muslim', 'obc', 'obc', 'unknown', 'unknown', 'obc', 'muslim', 'muslim', 'obc', 'obc', 'sc/st', 'obc', 'obc', 'sc/st', 'obc', 'unknown', 'general', 'obc', 'unknown', 'obc', 'muslim', 'unknown', 'obc', 'sc/st', 'obc', 'obc', 'unknown', 'obc', 'general', 'obc', 'unknown', 'obc', 'obc', 'unknown', 'unknown', 'muslim', 'sc/st', 'obc', 'unknown', 'muslim', 'obc', 'muslim', 'unknown', 'general', 'general', 'sc/st', 'muslim', 'general', 'obc', 'obc', 'obc', 'unknown', 'general', 'general', 'obc', 'muslim', 'sc/st', 'sc/st', 'sc/st', 'obc', 'general', 'unknown', 'obc', 'obc', 'obc', 'general', 'unknown', 'obc', 'sc/st', 'sc/st', 'obc', 'unknown', 'unknown', 'general', 'unknown', 'obc', 'obc', 'muslim', 'unknown', 'obc', 'muslim', 'obc', 'sc/st', 'unknown', 'general', 'unknown', 'obc', 'obc', 'obc', 'general', 'obc', 'unknown', 'general', 'general', 'unknown', 'muslim', 'unknown', 'general', 'sc/st', 'general', 'unknown', 'sc/st', 'unknown', 'general', 'sc/st', 'sc/st', 'obc', 'obc', 'general', 'obc', 'obc', 'muslim', 'muslim', 'obc', 'general', 'obc', 'unknown', 'sc/st', 'obc', 'obc', 'muslim', 'obc', 'obc', 'unknown', 'general', 'unknown', 'obc', 'sc/st', 'obc', 'sc/st', 'unknown', 'sc/st', 'unknown', 'obc', 'unknown', 'sc/st', 'unknown', 'sc/st', 'obc', 'general', 'obc', 'unknown', 'general', 'unknown', 'sc/st', 'unknown', 'sc/st', 'muslim', 'sc/st', 'general', 'unknown', 'obc', 'sc/st', 'obc', 'unknown', 'unknown', 'sc/st', 'obc', 'unknown', 'sc/st', 'unknown', 'obc', 'general', 'unknown', 'unknown', 'muslim', 'sc/st', 'obc', 'general', 'muslim', 'unknown', 'unknown', 'general', 'muslim', 'muslim', 'unknown', 'obc', 'muslim', 'obc', 'general', 'sc/st', 'obc', 'muslim', 'unknown', 'muslim', 'sc/st', 'sc/st', 'obc', 'general', 'obc', 'unknown', 'muslim', 'general', 'muslim', 'muslim', 'unknown', 'obc', 'unknown', 'muslim', 'obc', 'obc', 'obc', 'sc/st', 'muslim', 'unknown', 'general', 'muslim', 'unknown', 'sc/st', 'obc', 'muslim', 'unknown', 'muslim', 'sc/st', 'unknown', 'muslim', 'unknown', 'obc', 'muslim', 'unknown', 'sc/st', 'general', 'obc', 'unknown', 'unknown', 'obc', 'obc', 'obc', 'obc', 'obc', 'general', 'unknown', 'obc', 'general', 'obc', 'unknown', 'sc/st', 'general', 'unknown', 'unknown', 'muslim', 'sc/st', 'obc', 'unknown', 'unknown', 'obc', 'obc', 'obc', 'unknown', 'unknown', 'sc/st', 'obc', 'obc', 'sc/st', 'obc', 'sc/st', 'general', 'obc', 'obc', 'unknown', 'unknown', 'general', 'sc/st', 'general', 'unknown', 'general', 'general', 'sc/st', 'obc', 'muslim', 'general', 'obc', 'obc', 'general', 'unknown', 'unknown', 'sc/st', 'obc', 'unknown', 'obc', 'obc', 'obc', 'unknown', 'sc/st', 'obc', 'sc/st', 'unknown', 'unknown', 'sc/st', 'obc', 'obc', 'unknown', 'obc', 'sc/st', 'obc', 'muslim', 'obc', 'sc/st', 'unknown', 'obc', 'obc', 'obc', 'unknown', 'general', 'obc', 'obc', 'muslim', 'obc', 'obc', 'obc', 'general', 'sc/st', 'muslim', 'obc', 'sc/st', 'general', 'unknown', 'general', 'general', 'obc', 'general', 'unknown', 'general', 'sc/st', 'unknown', 'general', 'unknown', 'unknown', 'general', 'unknown', 'sc/st', 'unknown', 'general', 'general', 'sc/st', 'obc', 'obc', 'general', 'sc/st', 'unknown', 'obc', 'unknown', 'muslim', 'obc', 'unknown', 'unknown', 'obc', 'obc', 'sc/st', 'general', 'obc', 'sc/st', 'unknown', 'unknown', 'muslim', 'muslim', 'obc', 'general', 'general', 'sc/st', 'obc', 'obc', 'muslim', 'unknown', 'obc', 'unknown', 'muslim', 'unknown', 'unknown', 'obc', 'sc/st', 'muslim', 'unknown', 'general', 'obc', 'unknown', 'obc', 'general', 'sc/st', 'unknown', 'obc', 'general', 'obc', 'unknown', 'unknown', 'obc', 'unknown', 'muslim', 'general', 'unknown', 'muslim', 'muslim', 'muslim', 'unknown', 'muslim', 'unknown', 'general', 'unknown', 'sc/st', 'sc/st', 'general', 'sc/st', 'unknown', 'sc/st', 'sc/st', 'general', 'general', 'general', 'unknown', 'sc/st', 'unknown', 'obc', 'unknown', 'unknown', 'general', 'obc', 'muslim', 'general', 'sc/st', 'unknown', 'sc/st', 'general', 'muslim', 'unknown', 'muslim', 'obc', 'general', 'obc', 'sc/st', 'unknown', 'obc', 'sc/st', 'general', 'obc', 'unknown', 'obc', 'unknown', 'muslim', 'unknown', 'sc/st', 'unknown', 'sc/st', 'general', 'sc/st', 'general', 'obc', 'obc', 'general', 'unknown', 'obc', 'unknown', 'sc/st', 'unknown', 'unknown', 'obc', 'sc/st', 'unknown', 'general', 'general', 'obc', 'general', 'unknown', 'obc', 'general', 'sc/st', 'unknown', 'obc', 'unknown', 'sc/st', 'general', 'obc', 'unknown', 'unknown', 'general', 'sc/st', 'sc/st', 'sc/st', 'sc/st', 'sc/st', 'obc', 'obc', 'unknown', 'muslim', 'obc', 'unknown', 'muslim', 'sc/st', 'unknown', 'general', 'general', 'unknown', 'sc/st', 'sc/st', 'general', 'general', 'obc', 'general', 'obc', 'unknown', 'unknown', 'general', 'obc', 'sc/st', 'obc', 'unknown', 'obc', 'un

In [17]:
dict3 = {'Name':name1,'Cluster_caste':cluster1}
dict2 = {'Name':name2}
train_dataset = Dataset.from_dict(dict3)
test_dataset = Dataset.from_dict(dict2)
dataset1 = DatasetDict({
    "train": train_dataset,
    "test": test_dataset
})

from sklearn.preprocessing import LabelEncoder
le_cluster = LabelEncoder()
dataset1["train"] = dataset1["train"].add_column(
    "label_caste", le_cluster.fit_transform(dataset1["train"]["Cluster_caste"])
).remove_columns("Cluster_caste")
print(dataset1)
num_labels1 = len(le_cluster.classes_)
print(num_labels1)

DatasetDict({
    train: Dataset({
        features: ['Name', 'label_caste'],
        num_rows: 5000
    })
    test: Dataset({
        features: ['Name'],
        num_rows: 666
    })
})
5

In [18]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification
tokenizer = AutoTokenizer.from_pretrained("ai4bharat/indic-bert")
def tokenize(examples):
    return tokenizer(
        examples["Name"],
        padding="max_length",
        truncation=True
    )

dataset1 = dataset1.map(tokenize, batched=True)
model = AutoModelForSequenceClassification.from_pretrained(
    "ai4bharat/indic-bert",
    num_labels=num_labels1
)
import numpy as np

Map:   0%|          | 0/5000 [00:00<?, ? examples/s]

Map:   0%|          | 0/666 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/25 [00:00<?, ?it/s]

AlbertForSequenceClassification LOAD REPORT from: ai4bharat/indic-bert
Key                              | Status     |
---------------------------------+------------+-
predictions.decoder.bias         | UNEXPECTED |
sop_classifier.classifier.weight | UNEXPECTED |
sop_classifier.classifier.bias   | UNEXPECTED |
predictions.LayerNorm.weight     | UNEXPECTED |
predictions.LayerNorm.bias       | UNEXPECTED |
predictions.dense.bias           | UNEXPECTED |
predictions.dense.weight         | UNEXPECTED |
predictions.bias                 | UNEXPECTED |
predictions.decoder.weight       | UNEXPECTED |
classifier.weight                | MISSING    |
classifier.bias                  | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [19]:
print(dataset)

DatasetDict({
    train: Dataset({
        features: ['Name', 'label_caste', 'input_ids', 'attention_mask'],
        num_rows: 5000
    })
    test: Dataset({
        features: ['Name', 'input_ids', 'attention_mask'],
        num_rows: 666
    })
})

In [20]:
import evaluate
metric = evaluate.load("accuracy")
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    # convert the logits to their predicted class
    predictions = np.argmax(logits, axis=-1)
    return metric.compute(predictions=predictions, references=labels)
from transformers import TrainingArguments, DataCollatorWithPadding # Re-add DataCollatorWithPadding

training_args = TrainingArguments(
    output_dir="yelp_review_classifiersed",
    eval_strategy="epoch",
    push_to_hub=False,
    warmup_steps=0.13,
    learning_rate = 5e-5,
    adam_beta1=0.9,
    adam_beta2=0.999,
    adam_epsilon=3e-8,
    weight_decay=0.001,
    lr_scheduler_type = "linear",
    num_train_epochs=50
)
from transformers import Trainer

split = dataset1["train"].train_test_split(test_size=0.1)
train_dataset = split["train"]
eval_dataset = split["test"]
print(train_dataset)
train_dataset = train_dataset.rename_column("label_caste", "labels")
eval_dataset = eval_dataset.rename_column("label_caste", "labels")

train_dataset.set_format(type='torch', columns=['input_ids', 'attention_mask', 'labels'])
eval_dataset.set_format(type='torch', columns=['input_ids', 'attention_mask', 'labels'])

data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=eval_dataset,
    compute_metrics=compute_metrics,
    data_collator=data_collator
)

trainer.train()

Dataset({
    features: ['Name', 'label_caste', 'input_ids', 'attention_mask'],
    num_rows: 4500
})

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'Name': ['ABHAY', 'PANCHAL MANOJ ', 'GONSALVES SUNNY', 'AMRIT', 'BAISOYA RISHABH', 'GIRI HEMANT', 'KADIAN YOGESH', 'SINGH HARBHEJ', 'SINGH JOGA', 'SHARMA SACHIN', 'BAJAJ RITIK', 'SINGH BARJINDER', 'KUMAR ANIL', 'PATEL PRITESH MUKESHBHAI', 'JAIN HARSHIT BABULAL', 'SINGH VIKRAMJEET', 'SANGWAN KAPIL', 'SINGH SATINDERJEET', 'SANDHU HARWINDER SINGH', 'SINGH RANDEEP', 'KOLANJA MOHAMMAD RAFEEQ', 'PURUSHAN SUDHEESH KUMAR', 'HAIDER SYED MUHAMMAD ARSHIYAN', 'NANAVATI ADITYA', 'SINGH GURJINDER', 'GUPTA VIKASH', 'SANDHU SHAMINDER SINGH', 'RAIJADA KAVALJITSINH MAHENDRASINH', 'SINGH HARSAHIB', 'ANGOM SANATOMBA SINGH', 'PUKHRAMBAM SAMANANDA SINGH', 'KSHETRIMAYUM BROJEN SINGH', 'TAKHELAMBAM RAGHU', 'THOKCHOM GANDHI SINGH', 'SULTAN AYAZ MOHAMMED', 'ARMAR MOHAMMAD SHAFI', 'SINGH KARANVIR', 'SINGH AVTAR', 'SINGH HARMEET', 'RANPARIYA JAYSUKH', 'SINGH JANG BAHADUR', 'SINGH GURMIT', 'BHANSALI MIHIR RASHMI', 'SINGH GURPREET', 'SINGH MEHENGA', 'LAMKANG STARSON', 'MOIRANGTHEM TAMBA', 'KHURAIJAM MAIPAK', 'MUNSHI SHAIKH ZAHIDMIYA', 'CHERIYA VEETTIL SADIQUE', 'GOTTIPARTHI SRINIVAS', 'AHMED SADAB', 'SHEIKH ABU RASID', 'HUSSAIN ANWAR', 'RAJBHAR BALARAM', 'ISHAQI SALIM', 'MOHD KHALID', 'BEG MIRZA SHADAAB', 'ALAM DR. SHAHNAWAZ', 'ARMAR ABDUL KHADER SULTAN', 'NEHRA AJAY', 'SINGH DEVESH KUMAR', 'IQBAL L IWANTHABA', 'PATIL RUDRA', 'LIMKAR PRAVEEN', 'CHOUDHARY MOHSIN', 'KAGZI FAYAZ', 'T R CALVIN RAINGAM', 'BAINS AMANDEEP SINGH', 'SHAHABANDRI RIYAZ AHAMED', 'SHAIKH HASSAN LUKMAN', 'JAMATIA COMREDPADA', 'JOSEPH THARAKAN PARRAYIL GEORGE', 'KHAN MOHAMMED SHOEB', 'DOLA SALIM', 'SINGH AMRIK', 'SINGH GURTEJ', 'AHMED FAHIM', 'PATEL BHARATBHAI VIHABHAI', 'MODI NIRAV DEEPAK', 'SINGH RAJ', 'CHAUHAN RAM', 'TAMANG JAIY', 'THOUDAM SOMORENDRO SINGH', 'BHUTHAM GOVINDU', 'MALBARI ABDUL RASHEED HUSAIN SHEIK', 'SHETTY BALAKRISHNA', 'BHAT ZAFFAR HUSSAIN', 'SHERA UMAR FAROOQ', 'DAR NAZIR AHMAD', 'NAG ARUP', 'GOSAIN PRAMOD', 'BABU NURBASHA MOHAMMAD', 'MOHAMMED ABU SAAD', 'DEEPAK RANJAN', 'YOGISH', 'DIAS CLEMANT VICTOR', 'KUMAR SAJJAN', 'PATIDAR RAMCHANDRA KALSANGARA', 'DANGE SANDEEP VASUDEV', 'DEBBARMA BUDHRAI', 'SAYYED MUZAKKIR MUDDASSAR HUSAIN', 'GURSHARAN SINGH KALER', 'CHOUDHARY SANJAY KUMAR', 'PATEL RAFIQ', 'VIJAY SHYAM SHETTY', 'BHATKAL IQBAL', 'BHALLA RAKESH MOHAN', 'SREEDHARAN SUDHIN KUMAR', 'MARQUES INACIO', 'DEVDIWALA FAROOQ', 'SINGH RAVI PRAKASH', 'SINGH BHAGWANT', 'CHAURASIYA BRIJ BHUSHAN', 'DAWREY RIZWAN MOHAMMAD', 'SEKAR', 'AMARJIT SINGH AMBA', 'SHARIFKHAN PATHAN', 'DEBBARMA SACHINDRA', 'FAROOQUI ABDUL ARIF', 'SHARMA SURESH', 'CHOUGULE IRFAN', 'CHANDOK SURENDER SINGH', 'SHEIK DAWOOD SHAHUL HAMEED', 'KSHETRIMAYUM NOYON SINGH', 'NAMOIJAM OKENDRO SINGH', 'SUMI NIKI', 'BANGARD NAVAL KISHORE', 'SIDDIQ ABUBAKKAR', 'SUKHMINDER SINGH BAINS BHOLA', 'DEEPAK MANIKAN', 'KHAN GULAM NABI', 'DAR MANZOOR AHMAD', 'MAQBOOL PANDIT MOHD', 'NARENGBAM MARIJIT SINGH', 'VENKATA PRAVEEN KUMAR RAJULAPATI', 'NICOL TAMANG', 'JAGDISHBHAI PUNJIRAM', 'GHORI MOHAMMED FARHATULLAH', 'PATEL NATUBHAI SATABHAI', 'PATEL DILIPBHAI BABUBHAI', 'BATRA DAMINDER SINGH', 'SHANKARAN RAVI', 'BANGER JASWINDER SINGH', 'SYED ALMAS MAHARAJ', 'HANIF TIGER', 'AGRAWAL SURENDRA', 'GADGIL NANDAN PRABHAKAR', 'BARUAH PARESH', 'SHAIKH SHAKEEL', 'SHAIKH ANIS', 'KASKAR DAWOOD IBRAHIM', 'SIVARAMA KURUP SUKUMARAN', 'VISHWANATHA SHETTY', 'SINGH GURUDEV', 'PREM SETHI', 'ANSARI TAHER', 'MOHD YUSUF SHAH', 'SAYED ARIF', 'DOSA MOHAMED AHMED', 'BEDI SURENDER SINGH', 'CHANDOK HARLEEN KAUR', 'NAUSHA KADEEJATH', 'STANLY VARGHESE BHUVANESWARI', 'EDADAN OMANA', 'ABDUL ASIF ABDUL SADIK', 'ABDUL GAFFAR ABDUL KADAR', 'ABDUL KHAN AYUB KHAN', 'Abdul Rafique Abdul Kabir', 'ABDUL SAJID ABDUL SAMAR', 'ABDUL SALIM ALIAS BADSHAHA ABDUL SALAM', 'ABDUL SHAKIR ALIAS ABDUL RAZAK', 'ABDUL WAJID ABDUL KHALID', 'ABDUL WASIM ABDUL SALAM', 'ABHISHEK VIVEK DESHMUKH', 'AJAY ARUN JUNGHARE', 'AJAY PRAKASH DABHADE', 'AKASH HARIBHAU PARTEKI', 'Akash Ramesh Wankhade', 'AKHILESH JAYANTILAL AADTIYA', 'Akshay Alias Shirish Shivdatta Mate', 'AKSHAY SURESH CHARHATE', 'AMAR ARVIND BONDE', 'AMAR BHARAT WAWER', 'AMIT RAMNARAYAN TIWARI', 'AMOL BABURAO DANGE', 'AMOL BAPURAO DANGE', 'AMOL DAYANAND WASNIK', 'AMOL DYANESHWAR RAUT', 'ANIL BHAGWATRAO MOHANKAR', 'ANIL DASHRATH KHADSE', 'ANIL RAMRAO WANKHADE', 'ANKUSH WASUDEV THAKARE', 'ANSAR KHAN ALIAS TANTYA YUSUF KHAN', 'Ansar Khan Mahommad Khan', 'ARSHID KHAN RASHID KHAN', 'ARUN RAMDAS YEDATKAR', 'ASHISH BABAN DESHMUKH', 'ASHOK ALIAS CHOTU SAHDEVRAO INGALE', 'ASHOK SHYAMA BHOSALE', 'ASHWIN ASHOK WANKHADE', 'ATAULLAH KHAN BISMILLA KHAN', 'ATUL MURALIDHAR NAIK', 'AVINASH ASHOK BHUYAR', 'AZAHAR BEIG KADAR BEIG', 'BABARAO DADARAO HIVRALE', 'BABLU KHAN HASIL KHAN', 'BADSHAH AJABSING TANK', 'BADSHAHASINGH AJABSINGH TANK', 'BADSHAHASINGH AJABSINGH TANK', 'BALU GULAB MAHALLE', 'BANDYA KISAN KALE', 'BARAKYA ALIAS HANSRAJ PAWAR', 'BARKYA ALIAS RAJHANS JARTARI PAWAR', 'BATKYA JALTARI PAWAR', 'BHARAT MOHAN DIVATE', 'BHOLU ALIAS SHAKIRNUR MOHAMMAD', 'BHOLU MORE', 'BHURE KHAN RAFIQUE KHAN NOOR KHAN', 'Bhushan Pradip Baseriya', 'BUNTY ALIAS RAVI SHYAM ATHIYA', 'BUNTY SHOKRAO PAWAR', 'CHARAN MANIK LADE', 'DADARAO HIRAMAN RANGARI', 'DADASING ALIAS RAJASING AJABSING TANK', 'DARASING KISAN MALAVE', 'DEELIP KISANRAO WAGH', 'DEELIP RAM KORDE', 'DEELIP SHIVACHAND CHUDIWALA', 'DEEPAK MADAN PATIL', 'DHANRAJ RAMASWAMI ZIRPILLAI', 'DILBARSING JOHANSING TANK', 'DILDAR KHAN SATTAR KHAN', 'DILIP KISAN PUNASE', 'DINESH NAMDEV KHEDKAR', 'DINESH NAWANDAR', 'DIPAK ALIAS NAKTYA GENDALAL GUPTA', 'DIPAK SHRIRAM KALE', 'DIWAKAR GOWARDHAN KHADSE', 'DYANESHWAR VITTHAL KALANE', 'FATTUSINGH INDRASINGH MILL', 'FIRDAUS KHAN MEHABUB KHAN', 'GAFFARALI SATTARALI', 'GAJANAN ARUN ATRAM', 'GAJANAN CHALISA BHOSALE', 'GAJANAN DADARAO NEWARE', 'GAJANAN GOPALRAO INGOLE', 'GAJANAN HIMMATRAO KARALE', 'GAJANAN PRALHAD KALPANDE', 'GANESH BABARAO PURI', 'GAURAV GAJANAN KAMBE', 'GAUTAM MOTIRAM GHODESWAR', 'Golu Alias Swapnil Mukund Shinde', 'GOPAL BABAN SOLANKE', 'GOPAL MADHUKAR THORAT', 'GOPAL MADHUKAR THORAT', 'GOVIND NARAYAN SAHU', 'GUDDU ALIAS SHEIKH ANSAR SHEIKH SATTAR', 'GULAM HASAN AULAD HUSAIN', 'HARIKESH ALIAS GUDDU MADAN KATTILWAR', 'HARSHAL ALIAS BALA MURLIDHAR GAWALE', 'HEMRAJ BHALALIYA SASI', 'IMRAN KHAN ALIAS BABLU ARIF KHAN', 'IRFAN KHAN SHARIF KHAN', 'IRFAN KHAN SHARIQUE KHAN', 'IRFANUDDIN GULFARAZUDDIN', 'JACKY ALIAS JAYKISAN RUPRAO PARADE', 'JANARDHAN ALIAS JANYA ALIAS JOHNY RAMRAO WAGHMARE ALIAS RAJESH SAANE', 'JARNAILSINGH ALIAS RAHULSINGH JYOGENDRASINGH TANK', 'JAY VIJAYKUMAR SHARMA', 'JAYANDRA PRAKASH KALE', 'JAYANT PRAKASH KALE', 'JAYPRAKASH NANDLAL MARIYA', 'JITENDRA AJAY DHOKE', 'JITU ALIAS JITENDRA RAMRAO BHAGAT', 'JYOTISINGH UMRAOSINGH BABARI', 'Kailash Kuwarsingh Bheel', 'KAILASH RATANSING PAWAR', 'KALYA ALIAS RAKESH MANJU BABA TAMBOLE', 'KARAN CHOKHELAL SEN', 'KISAN SHESHRAO HANDE', 'KULDEEPSINGH DARSHANSINGH JUNNI', 'LAL ALIAS HAFIZ SHAH HABIB SHAH', 'LAXAM AMBADAS SOLANKE', 'LAXMI VIRANNA ZHIRPILLAI', 'LOKESH JARTARI PAWAR', 'MAHADEV BHIMRAO GHORMADE', 'MAHESH ALIAS AJAY RAJKAMAL SASI', 'MAHESH CHAUBITRAM JIVTANI', 'MAISUR TABJUL BEIG SAFJALUL BEIG', 'MANGA VIRANNA ZIRPILALU', 'MANGESH ALIAS KALOTYA DEELIP WAGHMARE', 'MANGESH RAMDAS MUNDANE', 'MANGESH TULSHIRAM RAUT', 'MANISH ALIAS BABLU KESHAV NAGPURE', 'MANISH ROSHANLAL PUROHIT', 'MANOJ BABULAL SOLANKE', 'MANOJ LAXMAN GONDANE', 'MEHAMUD SHAH MUSTAFA SHAH', 'MEHBUB KHAN HAYAT KHAN', 'MOHABBATSINGH KAURSINGH THAKUR', 'MOHAMAD IMRAN MOINUDDIN', 'MOHAMAD JAMIL ALI NUSARAT ALI', 'MOHAMAD VASIM ISMAIL', 'MOHAMMAD JAWED MOHAMMAD MIRZA', 'MOHAMMADSINGH PARVATSINGH', 'MOHSEEN KHAN HAMID KHAN', 'MOMIN KHAN RAHEMAT KHAN', 'MUKESH LAKSHAMSINGH THAKUR', 'MUKUND DURYODHAN WAWARE', 'NAGESH NAMDEV KHEDKAR', 'NAJAKAT ALIAS NAJJA SHEIKH BABA', 'NARAYAN ALIAS ARYAN KALURAM DEVKAR', 'NARAYAN KISAN PATAKE', 'NARENDRA PRAKASH DHAGE', 'NARESH PADMAKAR NANDESHWAR', 'NASIN KHAN ALIAS NAJJA RASHID KHAN', 'NIJAMUDDIN AJIJ KHAN', 'NIKHIL VIJAY TIKALE', 'NILESH DEELIP POTFODE', 'NILESH HARIVIJAY UGHADE', 'NILESH TUKARAM CHAVHATE', 'NITIN MADHUKAR MESHRAM', 'NITIN MAROTRAO NALHE', 'NITIN NARESH CHAVHAN', 'NITU NATTHU DAWANDE', 'OM MADAN CHAUDHARI', 'OMPRAKASH BHARAT BHATAKAR', 'PANJAB UTTAMRAO GAJBHIYE', 'PANKAJ ALIAS DEBU AVADHUT GAJBHIYE', 'PANKAJ GANESH BHURAI', 'PANKAJ RAJU GONDANE', 'PANKAJ RAMDAS DHOKE', 'PANKAJ SURESH TAYADE', 'PAVAN ALIAS BHOLU SHANKAR BARAD', 'PAVAN ANIL TIDAKE', 'PAVAN DINKAR GALE', 'PAVAN PRAKASHCHANDRA MATWANI', 'PAVAN RAMESH TOPALE', 'PINTYA KISAN BHANDE', 'PRABHAKAR NAGORAO BHOWALE', 'PRADIP PANDURANG SHENDE', 'PRAKASH ALIAS ANTHONY ALIAS THOMAS DHANDAR', 'PRAKASH CHANDRBHAN BENDRE', 'PRAKASH DINESH ATHAVALE', 'PRAKASH JIYALDAS MANWANI', 'PRALHAD DHNYANESHWAR GAYAKWAD', 'PRAMOD DEVRAO BANSOD', 'PRAMOD MAHADEV DHANADE', 'PRAMOD UTTAM DHOKE', 'PRATIK DHANRAJ ZADE', 'PRATIK NAMDEO SHINDE', 'PRAVIN ALIAS PINTYA BHIMYA BANSOD', 'PRAVIN TULSHIRAM KADU', 'PRITAM PANDURANG SURWANSHI', 'PRUTHVI ASHOK WANKHADE', 'RAHAMAT KHAN BISMILLA KHAN', 'RAHUL AMBADAS GETHE', 'RAHUL AMBADAS GETHE', 'RAHUL SUDHAKAR KHOBRAGADE', 'RAJABHAU BOBADE', 'RAJESH BABULAL SOLANKE', 'RAJESH NARAYAN BITAKARI', 'RAJU DATTOPANT ATHAVALE', 'RAJU HOTCHAND ADWANI', 'RAJU SHARAD KALE', 'Rakesh Gopal Gehalod', 'RAMJAN SHAHA TUKDU SHAHA', 'RANU ALIAS RANDEEP CHAINSUKH CHANGANI', 'RASHID KHAN ALIAS MUNGUS GAUSADAR KHAN', 'RAVI ALIAS MAMA LALLUN KHURKHURIYA', 'RAVI CHARAN PATIL', 'RAVI NARAYAN KHADASE', 'RAVINDRA ALIAS GOND SHIVDAS DHOKE', 'RAVINDRA HARIDAS PANEKAR', 'REHANA BANO AHAMAD SHAH', 'Rohit Ganeshrao Ajabe', 'ROSHAN DHASAKAT', 'ROSHAN SANJAY DESHMUKH', 'ROSHAN SURESH KHOBRAGADE', 'ROSHAN VINAYAK ROHANKAR', 'ROSHAN WASUDEV DHASKAT', 'RUPESH BANGADE', 'RUSHIKESH TULSHIRAM KANTALE', 'SACHIN BHASKAR LANJEWAR', 'SACHIN DINKAR CHAUDHARI', 'SACHIN SHRIKRUSHNA DESHMUKH', 'SACHIN WALKHADE', 'SAFDAR BEIG AZAGAR BEIG', 'SAGAR JANARDHAN GOGATE', 'SAGAR JANRAO WANKHADE', 'SAGAR NANAJI WANKHADE', 'SAGAR NARAYAN KHANDARE', 'SAGARSING MAYASING TANK', 'SAIF AHAMAD FARUK AHAMAD', 'SAIYAD ASIF SAIYAD BHURU', 'SAIYAD NIYAJ SAIYAD MUZHAFAR', 'SAIYAD SHAFIQUE SAIYAD RAFIQUE', 'SAIYAD SHAKIR SAIYAD BHURA', 'SALEM DASU GOGALU', 'SALIM KHAN ALIAS SALLU RAFIQUE KHAN', 'SAMAD SHAUKAT SAMAD ABDUL', 'SANDIP DADARAO PAHADAN', 'SANDIP KISAN VAIDYA', 'SANDIP RAMESH RAUT', 'SANDIP SHANKAR KSHIRSAGAR', 'SANGAM HANUMANT MESHRAM', 'SANGITA JADHAV', 'SANJAY ALIAS FANTER DHANSUKH BUDHWANI', 'SANJAY AMBADAS THOSARE', 'SANJAY DEELIP GHODE', 'SANJAY SHANKAR AWARE', 'SANTOSH BANSOD', 'SANTOSH KESHAV KINNAKE', 'SANTOSH SHALIKRAM GAYAKWAD', 'SATISH ALIAS GOLU PURUSHOTTAM SIDAM', 'SATISH ALIAS SATTYA UKADRAO KUROTIYA', 'SATISH BHAGATSINGH SOLANKE', 'SATTYA ALIAS SATISH UKANDRAO KUTORIYA', 'SHAKIR NUR MOHOMMAD KHAN', 'SHAMIULLA KHAN HAFIZULLA KHAN', 'SHAMMI SHAHA MURAD SHAHA', 'SHANKAR SUBHASH BANSOD', 'SHARIK ALI ASHAK ALI KHAN', 'SHASHIKANT PRABHUDAYAL UPADDHYAY', 'SHASHIKUMAR SAHEBRAO TATTE', 'SHEIKH ANSAR NIYAJ ALI', 'SHEIKH ARIF ALIAS GUDDU SHEIKH YUSUF', 'SHEIKH ARIF SHEIKH MUSUD', 'SHEIKH ASIF SHEIKH GUDDU', 'SHEIKH AYUB SHEIKH IBRAHIM', 'SHEIKH CHAND SHEIKH BHURU', 'SHEIKH CHHOTU ARIF SHEIKH DILAWAR', 'SHEIKH CHOTU SHEIKH DILAWAR', 'SHEIKH FIROZ SHEIKH YAKUB', 'SHEIKH GOLU SHEIKH BABA', 'SHEIKH GOLU SHEIKH KADAR', 'SHEIKH HAMID ALIAS MOTU SHEIKH HANIF', 'SHEIKH HAMID ALIAS MOTU SHEIKH HANIF', 'SHEIKH HASAN SHEIKH HUSAIN', 'SHEIKH IRAFAN SHEIKH BISMILLAH', 'SHEIKH JAFAR SHEIKH KARIM', 'SHEIKH JAVED SHEIKH BHURU', 'SHEIKH JAWED ALIAS DADU SHEIKH SABIR', 'SHEIKH JAWED SHEIKH BHURU', 'SHEIKH MATIN SHEIKH MEHABUB', 'SHEIKH RAFIQUE NABIULLA SHEIKH ALIAS SHEKHAR PATIL', 'SHEIKH RIZWAN ALIAS MUNNA MOBILE SHEIKH JALIL', 'SHEIKH SABIR SHEIKH IMAM', 'Sheikh Salman Sheikh Shakur', 'Sheikh Shahid Sheikh Chand', 'SHEIKH TOUFIQUE SHEIKH RAFIQUE', 'SHIVA ALIAS SHIVAJI VITTHAL BHOSALE ALIAS BHOLE', 'SHOBI ALIAS SHOHEB BABBU SARPANCH', 'SHRIKRUSHANA PINTYA DEVIDAS GAHUKAR', 'SHUBHAM GAJANAN SAYANKE', 'SHYAM GAJANAN PURI', 'SHYAM MADAN PATHAK', 'SINNA CHINNA ATAPALLI', 'SONYA ALIAS MANGESH BHIMRAO CHANDURKAR', 'SUBODH BHIMARAO DHAKADE', 'SUDHIR DADARAO PUND', 'SUDHIR LAXMAN JAVANJAL', 'SUDHIR SURESH LAHUPANCHANG', 'SUHAS ALIAS PRAKASH ASHOK JOSHI', 'SUNIL JAYDEV MESHRAM', 'SUNIL PRAKASH GULSUNDARE', 'SUNIL SHANKARRAO MATE', 'SUNIL SHYAMRAO UKE', 'SUNNY SUNIL BIJAVE', 'SURAJ GAJANAN DESHKAR', 'SURAJ PURUSHOTTAM GUPTA', 'SURENDRA RAOSAHEB KORE', 'SURENDRA UDHAVRAO WAKODE', 'SURESH PRAKASH RANGARI', 'SURESH SUDHAKAR GANDHE', 'SUSHANT ARUN GANJARE', 'SUSHIL ALIAS KHANDYA WANKHADE', 'SUYASH CHANDRASHEKHAR DORLE', 'SWAPNIL MOTIRAM MESHRAM', 'Swapnil Vinay Bangre', 'TAANYA ALIAS TANAJI VITTHAL BHOSALE', 'TIRUMALLI WALKISAN ATAPALLI', 'UJWAL ALIAS SONU SHEKHAR KAMKARE', 'UMESH BHUJANGRAO MAHALLE', 'VASIM KHAN YUSUF KHAN', 'VIJAY NAJUK INGALE', 'Vijay Pandurang Raybole', 'VIJAY SANJAY SURYAWANSHI', 'VIJAY TULASHIRAM KALE', 'VIKAS RAMJI CHAPALKAR', 'VIKKY ALIAS ASHOK GANOSKAR', 'VIKKY DHANARAJ KHANDARE', 'VIKKY RAJENDRA GADLING', 'VINOD ARUN KOTHE', 'VIRANNA BANKKATAPPA ZIRPILALU', 'VISHAL ARUN PAWAR', 'VITTHAL SHANKARAO MANKAR', 'Vivek Alias Bikku Ravindra Pande', 'VIVEK ALIAS BODYA VINAYAK NIRMAL', 'WAHID KHAN SAID KHAN', 'WAMAN JAGAN NAIK', 'WASANT SHANKAR CHAUDHARI', 'YOGESH ALIAS LAKHAN RAMESH WANKHADE', 'YOGESH GOVIND TAYADE', 'YUSUF ALI ASHAF ALI KHAN', 'ZAHIR SHEKHU KHURSHID ABBAS', 'ZAKIR HUSAIN JINNATALI', 'RAJESH KUMAR', 'Shri Deepankar Barman', 'Shr Hasen Ali', 'Shri Mohibul Prodhani', 'Azirul Islam alias Aziul Hoque', 'Shri Sunil Gogoi', 'Shahabaj Jakaria Shikdar', 'Ferdynald Kharkamni', 'Shri Arun Kumar Jain', 'Shri Santanu Mizar', 'Shri Amit Paul', 'Shri Lakstar Khariap', 'Shri Pujam Gurung', 'Shri Tilok Dorjee', 'Shri Mukhiya Singh', 'Shri Jhuggo Jasoda', 'Shri Shanborlang Rani alias Dengdeng', 'Shri Rohit', 'Bringo Lyngdoh', 'Nayan Bhattacharjee', 'Shri Sandeep Sunar', 'Shri Din Dayal Sharma', 'Shri Harlal Jat', 'Shri Majidul Khan', 'Shri Dilip Baspor', 'Shri Eyahia Ahmed', 'Shri Biswajit Yadav', 'Shri Amit Ghosh', 'Shri Mithun Sharma', 'Shri Nihar Ranjan Bhattachariya ', 'Shri Santosh Hajong ', 'Smti Balarisa Nengnong', 'Shri Diganta Kumar Adhikari', 'Shri Dilip Kumar', 'Shri Arjun Burman', 'SHRI DANIEL HAWK ', 'Shri Ramesh Gurung ', 'Smti Anandi Chapagai', 'Shri Khimananda Chapagai', 'Biswng Prasad Chattri', 'Shri Tapan Ojha', 'Shri Manseng D Sangma', 'Shri Lalit Dey', 'Shri Nur Mohmmed', 'Shri Asraful Ali', 'Shri Babeshor Kalandi', 'Shri Rex Briller R Marak', 'Miss Eunice Zimik', 'Shri Prema', 'Shri Shynsharlang Thongni', 'Shri Sumon Namo ', 'Smti Jesica Kharkongor ', 'Shri Mukesh Sangma', 'Bhim Singh', 'Shri Konesshon Rodborn ', 'Shri Thoudam Prasanta Singh  ', 'Chatu', 'Madhurendra Singh', 'Rousan', 'Bablu Rewani', 'Sunil Madni', 'Tribeni Prasad', 'Guljar Ansari', 'Samim', 'Kishore Mondal', 'Sakir Ansari', 'MD. SIRAJ', 'MD. NAUSHAD KHAN', 'MD. AKTAR KHAN', 'AKBAR KHAN', 'PABAN KUMAR YADAV', 'AMIT KUMAR YADAV', 'KALIYA KURMI', 'PINTU DEY', 'DHARMENDRA', 'UJJAL BOURI', 'MD NAWSAD', 'CASHIER', 'SK. LAL', 'RAKESH HELA', 'RAJESH VERMA', 'NANDA BOURI', 'KRISHNA DAS', 'KARA RAJ BANGSI', 'KRISHNA YADAV', 'BAIJU PRASAD RAM', 'LOKE NATH MUKHERJEE', 'SUBRATA SARKAR', 'PRITAM DAS', 'RANJIT HELA', 'RAJU RUIDAS', 'RAJU BOURI', 'RAHUL YADAV', 'PINTU RUIDAS', 'LAXMAN LAMA', 'LACHMI SAHANI', 'KARKAT DAS', 'JOGI DAS', 'GOUR SENGUPTA', 'BHALTU PASI', 'BESAN RUIDAS', 'BALDEV TURI', 'AUSTA RUIDAS', 'ANAND PASWAN', 'TIPU ANSARI', 'SUSHIL RAM', 'SURAJIT SARKAR', 'SK TAHIR', 'SK  SAMSOL', 'SK MOHIBUL', 'SK KHALID', 'SK IMAMUL', 'SK ILIAS', 'SK ASHRAF', 'SK AKHTAR', 'SK ABAR ALI', 'SARUDDIN', 'PRADIP KR TIWARI', 'MRINAL KANTI GHOSH', 'MOHAN RUIDAS', 'MD SHANAWAR', 'MD RIZWAN', 'MD NOUSAD', 'MD-IMTIYAJ', 'MANOJ-DOM', 'UTPAL-GHOSH', 'JITEN-PAUL', 'BADYANATH MONDAL', 'BURO BOURI', 'BIRJU PASWAN', 'SANJOY KR SUKLA', 'Mithilesh Kumar Singh', 'Khusbu', 'Rajesh Paswan', 'Manoj Mallick', 'Amar Mahato', 'MOHAN', 'Kanahi Bouri', 'Nimai Ruidas', 'Sanjoy Ruidas', 'Santosh Rewani', 'Sushil', 'Srimanta Ruidas', 'Manik Das', 'Rahul', 'RAJU', 'Gour', 'Raju Bauri', 'Besan', 'Bhaltu', 'Kartak Das', 'Jogi', 'Lachmi', 'Anand Paswan', 'Austa', 'Astik', 'BALDV TURI', 'LAXMAN'], 'Cluster': [np.str_('ACHRAY (SHARMA)'), np.str_('ACHRAY (SHARMA)'), np.str_('ACHRAY (SHARMA)'), np.str_('ADIWAL HARIJAN'), np.str_('ADIWAL HARIJAN'), np.str_('ACHRAY (SHARMA)'), np.str_('ADIWAL HARIJAN'), np.str_('AACHARIYA'), np.str_('AACHARIYA'), np.str_('ADIWAL HARIJAN'), np.str_('ACHARY'), np.str_('ADIWAL HARIJAN'), np.str_('ADIWAL HARIJAN'), np.str_('AACHARIYA'), np.str_('AACHARIYA'), np.str_('ADIWAL HARIJAN'), np.str_('ACHARYA'), np.str_('ACHARYA'), np.str_('AACHARIYA'), np.str_('ACHARYA'), np.str_('ACHARY'), np.str_('AACHARIYA'), np.str_('ACHARY'), np.str_('ACHRAY (SHARMA)'), np.str_('ADIWAL HARIJAN'), np.str_('ADIWAL HARIJAN'), np.str_('ACHARYA'), np.str_('AACHARIYA'), np.str_('AACHARIYA'), np.str_('AACHARIYA'), np.str_('AACHARIYA'), np.str_('AACHARIYA'), np.str_('ADIWAL HARIJAN'), np.str_('AACHARIYA'), np.str_('ACHARY'), np.str_('ACHARY'), np.str_('ACHARYA'), np.str_('AACHARIYA'), np.str_('ADIWAL HARIJAN'), np.str_('ACHARYA'), np.str_('AACHARIYA'), np.str_('ACHARYA'), np.str_('ACHARY'), np.str_('ACHARYA'), np.str_('ADIWAL HARIJAN'), np.str_('ADIWAL HARIJAN'), np.str_('ACHARY'), np.str_('ACHARY'), np.str_('ACHARY'), np.str_('ADIWAL HARIJAN'), np.str_('ADIWAL HARIJAN'), np.str_('ACHARY'), np.str_('ACHARY'), np.str_('ADIWAL HARIJAN'), np.str_('ACHARYA'), np.str_('ACHARY'), np.str_('ACHARY'), np.str_('ACHARY'), np.str_('ACHARY'), np.str_('ACHARY'), np.str_('ACHRAY (SHARMA)'), np.str_('ACHARYA'), np.str_('ACHARY'), np.str_('ACHARYA'), np.str_('ACHARYA'), np.str_('ACHARY'), np.str_('ACHARY'), np.str_('ADIWAL HARIJAN'), np.str_('ACHARYA'), np.str_('ACHARY'), np.str_('ACHARY'), np.str_('ADIWAL HARIJAN'), np.str_('AACHARIYA'), np.str_('ACHARY'), np.str_('ACHARY'), np.str_('ADIWAL HARIJAN'), np.str_('AACHARIYA'), np.str_('ACHARY'), np.str_('ACHARYA'), np.str_('ADIWAL HARIJAN'), np.str_('AACHARIYA'), np.str_('ACHRAY (SHARMA)'), np.str_('ADIWAL HARIJAN'), np.str_('AACHARIYA'), np.str_('AACHARIYA'), np.str_('ACHARY'), np.str_('ADIWAL HARIJAN'), np.str_('ACHARY'), np.str_('ACHARY'), np.str_('ACHARY'), np.str_('AACHARIYA'), np.str_('ADIWAL HARIJAN'), np.str_('ACHARY'), np.str_('ACHARY'), np.str_('ACHRAY (SHARMA)'), np.str_('ADIWAL HARIJAN'), np.str_('ACHRAY (SHARMA)'), np.str_('ADIWAL HARIJAN'), np.str_('ACHARYA'), np.str_('ACHARYA'), np.str_('ADIWAL HARIJAN'), np.str_('ACHARY'), np.str_('ACHARYA'), np.str_('ACHARYA'), np.str_('ACHARY'), np.str_('ADIWAL HARIJAN'), np.str_('ACHARY'), np.str_('ADIWAL HARIJAN'), np.str_('ACHRAY (SHARMA)'), np.str_('ADIWAL HARIJAN'), np.str_('ACHARY'), np.str_('AACHARIYA'), np.str_('AACHARIYA'), np.str_('ACHARYA'), np.str_('ACHARY'), np.str_('ADIWAL HARIJAN'), np.str_('ACHARYA'), np.str_('ACHARY'), np.str_('AACHARIYA'), np.str_('ACHARY'), np.str_('ADIWAL HARIJAN'), np.str_('ACHARY'), np.str_('AACHARIYA'), np.str_('ACHARY'), np.str_('AACHARIYA'), np.str_('AACHARIYA'), np.str_('ADIWAL HARIJAN'), np.str_('AACHARIYA'), np.str_('ACHARY'), np.str_('ACHARYA'), np.str_('ADIWAL HARIJAN'), np.str_('ACHARY'), np.str_('ACHARY'), np.str_('ACHARY'), np.str_('AACHARIYA'), np.str_('ACHARYA'), np.str_('ADIWAL HARIJAN'), np.str_('ACHARYA'), np.str_('ACHARY'), np.str_('ACHARYA'), np.str_('ACHARYA'), np.str_('AACHARIYA'), np.str_('ACHRAY (SHARMA)'), np.str_('ADIWAL HARIJAN'), np.str_('ADIWAL HARIJAN'), np.str_('ACHARY'), np.str_('ADIWAL HARIJAN'), np.str_('ACHARYA'), np.str_('ACHARY'), np.str_('ACHARY'), np.str_('ACHARY'), np.str_('ACHARY'), np.str_('AACHARIYA'), np.str_('ADIWAL HARIJAN'), np.str_('ACHARYA'), np.str_('AACHARIYA'), np.str_('ACHARY'), np.str_('ACHARY'), np.str_('ACHARY'), np.str_('ACHARY'), np.str_('AACHARIYA'), np.str_('AACHARIYA'), np.str_('AACHARIYA'), np.str_('AACHARIYA'), np.str_('ADIWAL HARIJAN'), np.str_('ACHARY'), np.str_('ACHARY'), np.str_('ACHARY'), np.str_('ACHARY'), np.str_('ADIWAL HARIJAN'), np.str_('ACHARY'), np.str_('ACHARY'), np.str_('ADIWAL HARIJAN'), np.str_('ACHARY'), np.str_('AACHARIYA'), np.str_('AACHAR

In [22]:
pred_results = trainer.predict(dataset["test"])
pred_labels = np.argmax(pred_results.predictions, axis=-1)
pred_categories = [le_cluster.classes_[i] for i in pred_labels]
dict2["Cluster"] = pred_categories
print(dict2['Name'])
print(dict2['Cluster'])

['ABHAY', 'PANCHAL MANOJ ', 'GONSALVES SUNNY', 'AMRIT', 'BAISOYA RISHABH', 'GIRI HEMANT', 'KADIAN YOGESH', 'SINGH HARBHEJ', 'SINGH JOGA', 'SHARMA SACHIN', 'BAJAJ RITIK', 'SINGH BARJINDER', 'KUMAR ANIL', 'PATEL PRITESH MUKESHBHAI', 'JAIN HARSHIT BABULAL', 'SINGH VIKRAMJEET', 'SANGWAN KAPIL', 'SINGH SATINDERJEET', 'SANDHU HARWINDER SINGH', 'SINGH RANDEEP', 'KOLANJA MOHAMMAD RAFEEQ', 'PURUSHAN SUDHEESH KUMAR', 'HAIDER SYED MUHAMMAD ARSHIYAN', 'NANAVATI ADITYA', 'SINGH GURJINDER', 'GUPTA VIKASH', 'SANDHU SHAMINDER SINGH', 'RAIJADA KAVALJITSINH MAHENDRASINH', 'SINGH HARSAHIB', 'ANGOM SANATOMBA SINGH', 'PUKHRAMBAM SAMANANDA SINGH', 'KSHETRIMAYUM BROJEN SINGH', 'TAKHELAMBAM RAGHU', 'THOKCHOM GANDHI SINGH', 'SULTAN AYAZ MOHAMMED', 'ARMAR MOHAMMAD SHAFI', 'SINGH KARANVIR', 'SINGH AVTAR', 'SINGH HARMEET', 'RANPARIYA JAYSUKH', 'SINGH JANG BAHADUR', 'SINGH GURMIT', 'BHANSALI MIHIR RASHMI', 'SINGH GURPREET', 'SINGH MEHENGA', 'LAMKANG STARSON', 'MOIRANGTHEM TAMBA', 'KHURAIJAM MAIPAK', 'MUNSHI SHAIKH ZAHIDMIYA', 'CHERIYA VEETTIL SADIQUE', 'GOTTIPARTHI SRINIVAS', 'AHMED SADAB', 'SHEIKH ABU RASID', 'HUSSAIN ANWAR', 'RAJBHAR BALARAM', 'ISHAQI SALIM', 'MOHD KHALID', 'BEG MIRZA SHADAAB', 'ALAM DR. SHAHNAWAZ', 'ARMAR ABDUL KHADER SULTAN', 'NEHRA AJAY', 'SINGH DEVESH KUMAR', 'IQBAL L IWANTHABA', 'PATIL RUDRA', 'LIMKAR PRAVEEN', 'CHOUDHARY MOHSIN', 'KAGZI FAYAZ', 'T R CALVIN RAINGAM', 'BAINS AMANDEEP SINGH', 'SHAHABANDRI RIYAZ AHAMED', 'SHAIKH HASSAN LUKMAN', 'JAMATIA COMREDPADA', 'JOSEPH THARAKAN PARRAYIL GEORGE', 'KHAN MOHAMMED SHOEB', 'DOLA SALIM', 'SINGH AMRIK', 'SINGH GURTEJ', 'AHMED FAHIM', 'PATEL BHARATBHAI VIHABHAI', 'MODI NIRAV DEEPAK', 'SINGH RAJ', 'CHAUHAN RAM', 'TAMANG JAIY', 'THOUDAM SOMORENDRO SINGH', 'BHUTHAM GOVINDU', 'MALBARI ABDUL RASHEED HUSAIN SHEIK', 'SHETTY BALAKRISHNA', 'BHAT ZAFFAR HUSSAIN', 'SHERA UMAR FAROOQ', 'DAR NAZIR AHMAD', 'NAG ARUP', 'GOSAIN PRAMOD', 'BABU NURBASHA MOHAMMAD', 'MOHAMMED ABU SAAD', 'DEEPAK RANJAN', 'YOGISH', 'DIAS CLEMANT VICTOR', 'KUMAR SAJJAN', 'PATIDAR RAMCHANDRA KALSANGARA', 'DANGE SANDEEP VASUDEV', 'DEBBARMA BUDHRAI', 'SAYYED MUZAKKIR MUDDASSAR HUSAIN', 'GURSHARAN SINGH KALER', 'CHOUDHARY SANJAY KUMAR', 'PATEL RAFIQ', 'VIJAY SHYAM SHETTY', 'BHATKAL IQBAL', 'BHALLA RAKESH MOHAN', 'SREEDHARAN SUDHIN KUMAR', 'MARQUES INACIO', 'DEVDIWALA FAROOQ', 'SINGH RAVI PRAKASH', 'SINGH BHAGWANT', 'CHAURASIYA BRIJ BHUSHAN', 'DAWREY RIZWAN MOHAMMAD', 'SEKAR', 'AMARJIT SINGH AMBA', 'SHARIFKHAN PATHAN', 'DEBBARMA SACHINDRA', 'FAROOQUI ABDUL ARIF', 'SHARMA SURESH', 'CHOUGULE IRFAN', 'CHANDOK SURENDER SINGH', 'SHEIK DAWOOD SHAHUL HAMEED', 'KSHETRIMAYUM NOYON SINGH', 'NAMOIJAM OKENDRO SINGH', 'SUMI NIKI', 'BANGARD NAVAL KISHORE', 'SIDDIQ ABUBAKKAR', 'SUKHMINDER SINGH BAINS BHOLA', 'DEEPAK MANIKAN', 'KHAN GULAM NABI', 'DAR MANZOOR AHMAD', 'MAQBOOL PANDIT MOHD', 'NARENGBAM MARIJIT SINGH', 'VENKATA PRAVEEN KUMAR RAJULAPATI', 'NICOL TAMANG', 'JAGDISHBHAI PUNJIRAM', 'GHORI MOHAMMED FARHATULLAH', 'PATEL NATUBHAI SATABHAI', 'PATEL DILIPBHAI BABUBHAI', 'BATRA DAMINDER SINGH', 'SHANKARAN RAVI', 'BANGER JASWINDER SINGH', 'SYED ALMAS MAHARAJ', 'HANIF TIGER', 'AGRAWAL SURENDRA', 'GADGIL NANDAN PRABHAKAR', 'BARUAH PARESH', 'SHAIKH SHAKEEL', 'SHAIKH ANIS', 'KASKAR DAWOOD IBRAHIM', 'SIVARAMA KURUP SUKUMARAN', 'VISHWANATHA SHETTY', 'SINGH GURUDEV', 'PREM SETHI', 'ANSARI TAHER', 'MOHD YUSUF SHAH', 'SAYED ARIF', 'DOSA MOHAMED AHMED', 'BEDI SURENDER SINGH', 'CHANDOK HARLEEN KAUR', 'NAUSHA KADEEJATH', 'STANLY VARGHESE BHUVANESWARI', 'EDADAN OMANA', 'ABDUL ASIF ABDUL SADIK', 'ABDUL GAFFAR ABDUL KADAR', 'ABDUL KHAN AYUB KHAN', 'Abdul Rafique Abdul Kabir', 'ABDUL SAJID ABDUL SAMAR', 'ABDUL SALIM ALIAS BADSHAHA ABDUL SALAM', 'ABDUL SHAKIR ALIAS ABDUL RAZAK', 'ABDUL WAJID ABDUL KHALID', 'ABDUL WASIM ABDUL SALAM', 'ABHISHEK VIVEK DESHMUKH', 'AJAY ARUN JUNGHARE', 'AJAY PRAKASH DABHADE', 'AKASH HARIBHAU PARTEKI', 'Akash Ramesh Wankhade', 'AKHILESH JAYANTILAL AADTIYA', 'Akshay Alias Shirish Shivdatta Mate', 'AKSHAY SURESH CHARHATE', 'AMAR ARVIND BONDE', 'AMAR BHARAT WAWER', 'AMIT RAMNARAYAN TIWARI', 'AMOL BABURAO DANGE', 'AMOL BAPURAO DANGE', 'AMOL DAYANAND WASNIK', 'AMOL DYANESHWAR RAUT', 'ANIL BHAGWATRAO MOHANKAR', 'ANIL DASHRATH KHADSE', 'ANIL RAMRAO WANKHADE', 'ANKUSH WASUDEV THAKARE', 'ANSAR KHAN ALIAS TANTYA YUSUF KHAN', 'Ansar Khan Mahommad Khan', 'ARSHID KHAN RASHID KHAN', 'ARUN RAMDAS YEDATKAR', 'ASHISH BABAN DESHMUKH', 'ASHOK ALIAS CHOTU SAHDEVRAO INGALE', 'ASHOK SHYAMA BHOSALE', 'ASHWIN ASHOK WANKHADE', 'ATAULLAH KHAN BISMILLA KHAN', 'ATUL MURALIDHAR NAIK', 'AVINASH ASHOK BHUYAR', 'AZAHAR BEIG KADAR BEIG', 'BABARAO DADARAO HIVRALE', 'BABLU KHAN HASIL KHAN', 'BADSHAH AJABSING TANK', 'BADSHAHASINGH AJABSINGH TANK', 'BADSHAHASINGH AJABSINGH TANK', 'BALU GULAB MAHALLE', 'BANDYA KISAN KALE', 'BARAKYA ALIAS HANSRAJ PAWAR', 'BARKYA ALIAS RAJHANS JARTARI PAWAR', 'BATKYA JALTARI PAWAR', 'BHARAT MOHAN DIVATE', 'BHOLU ALIAS SHAKIRNUR MOHAMMAD', 'BHOLU MORE', 'BHURE KHAN RAFIQUE KHAN NOOR KHAN', 'Bhushan Pradip Baseriya', 'BUNTY ALIAS RAVI SHYAM ATHIYA', 'BUNTY SHOKRAO PAWAR', 'CHARAN MANIK LADE', 'DADARAO HIRAMAN RANGARI', 'DADASING ALIAS RAJASING AJABSING TANK', 'DARASING KISAN MALAVE', 'DEELIP KISANRAO WAGH', 'DEELIP RAM KORDE', 'DEELIP SHIVACHAND CHUDIWALA', 'DEEPAK MADAN PATIL', 'DHANRAJ RAMASWAMI ZIRPILLAI', 'DILBARSING JOHANSING TANK', 'DILDAR KHAN SATTAR KHAN', 'DILIP KISAN PUNASE', 'DINESH NAMDEV KHEDKAR', 'DINESH NAWANDAR', 'DIPAK ALIAS NAKTYA GENDALAL GUPTA', 'DIPAK SHRIRAM KALE', 'DIWAKAR GOWARDHAN KHADSE', 'DYANESHWAR VITTHAL KALANE', 'FATTUSINGH INDRASINGH MILL', 'FIRDAUS KHAN MEHABUB KHAN', 'GAFFARALI SATTARALI', 'GAJANAN ARUN ATRAM', 'GAJANAN CHALISA BHOSALE', 'GAJANAN DADARAO NEWARE', 'GAJANAN GOPALRAO INGOLE', 'GAJANAN HIMMATRAO KARALE', 'GAJANAN PRALHAD KALPANDE', 'GANESH BABARAO PURI', 'GAURAV GAJANAN KAMBE', 'GAUTAM MOTIRAM GHODESWAR', 'Golu Alias Swapnil Mukund Shinde', 'GOPAL BABAN SOLANKE', 'GOPAL MADHUKAR THORAT', 'GOPAL MADHUKAR THORAT', 'GOVIND NARAYAN SAHU', 'GUDDU ALIAS SHEIKH ANSAR SHEIKH SATTAR', 'GULAM HASAN AULAD HUSAIN', 'HARIKESH ALIAS GUDDU MADAN KATTILWAR', 'HARSHAL ALIAS BALA MURLIDHAR GAWALE', 'HEMRAJ BHALALIYA SASI', 'IMRAN KHAN ALIAS BABLU ARIF KHAN', 'IRFAN KHAN SHARIF KHAN', 'IRFAN KHAN SHARIQUE KHAN', 'IRFANUDDIN GULFARAZUDDIN', 'JACKY ALIAS JAYKISAN RUPRAO PARADE', 'JANARDHAN ALIAS JANYA ALIAS JOHNY RAMRAO WAGHMARE ALIAS RAJESH SAANE', 'JARNAILSINGH ALIAS RAHULSINGH JYOGENDRASINGH TANK', 'JAY VIJAYKUMAR SHARMA', 'JAYANDRA PRAKASH KALE', 'JAYANT PRAKASH KALE', 'JAYPRAKASH NANDLAL MARIYA', 'JITENDRA AJAY DHOKE', 'JITU ALIAS JITENDRA RAMRAO BHAGAT', 'JYOTISINGH UMRAOSINGH BABARI', 'Kailash Kuwarsingh Bheel', 'KAILASH RATANSING PAWAR', 'KALYA ALIAS RAKESH MANJU BABA TAMBOLE', 'KARAN CHOKHELAL SEN', 'KISAN SHESHRAO HANDE', 'KULDEEPSINGH DARSHANSINGH JUNNI', 'LAL ALIAS HAFIZ SHAH HABIB SHAH', 'LAXAM AMBADAS SOLANKE', 'LAXMI VIRANNA ZHIRPILLAI', 'LOKESH JARTARI PAWAR', 'MAHADEV BHIMRAO GHORMADE', 'MAHESH ALIAS AJAY RAJKAMAL SASI', 'MAHESH CHAUBITRAM JIVTANI', 'MAISUR TABJUL BEIG SAFJALUL BEIG', 'MANGA VIRANNA ZIRPILALU', 'MANGESH ALIAS KALOTYA DEELIP WAGHMARE', 'MANGESH RAMDAS MUNDANE', 'MANGESH TULSHIRAM RAUT', 'MANISH ALIAS BABLU KESHAV NAGPURE', 'MANISH ROSHANLAL PUROHIT', 'MANOJ BABULAL SOLANKE', 'MANOJ LAXMAN GONDANE', 'MEHAMUD SHAH MUSTAFA SHAH', 'MEHBUB KHAN HAYAT KHAN', 'MOHABBATSINGH KAURSINGH THAKUR', 'MOHAMAD IMRAN MOINUDDIN', 'MOHAMAD JAMIL ALI NUSARAT ALI', 'MOHAMAD VASIM ISMAIL', 'MOHAMMAD JAWED MOHAMMAD MIRZA', 'MOHAMMADSINGH PARVATSINGH', 'MOHSEEN KHAN HAMID KHAN', 'MOMIN KHAN RAHEMAT KHAN', 'MUKESH LAKSHAMSINGH THAKUR', 'MUKUND DURYODHAN WAWARE', 'NAGESH NAMDEV KHEDKAR', 'NAJAKAT ALIAS NAJJA SHEIKH BABA', 'NARAYAN ALIAS ARYAN KALURAM DEVKAR', 'NARAYAN KISAN PATAKE', 'NARENDRA PRAKASH DHAGE', 'NARESH PADMAKAR NANDESHWAR', 'NASIN KHAN ALIAS NAJJA RASHID KHAN', 'NIJAMUDDIN AJIJ KHAN', 'NIKHIL VIJAY TIKALE', 'NILESH DEELIP POTFODE', 'NILESH HARIVIJAY UGHADE', 'NILESH TUKARAM CHAVHATE', 'NITIN MADHUKAR MESHRAM', 'NITIN MAROTRAO NALHE', 'NITIN NARESH CHAVHAN', 'NITU NATTHU DAWANDE', 'OM MADAN CHAUDHARI', 'OMPRAKASH BHARAT BHATAKAR', 'PANJAB UTTAMRAO GAJBHIYE', 'PANKAJ ALIAS DEBU AVADHUT GAJBHIYE', 'PANKAJ GANESH BHURAI', 'PANKAJ RAJU GONDANE', 'PANKAJ RAMDAS DHOKE', 'PANKAJ SURESH TAYADE', 'PAVAN ALIAS BHOLU SHANKAR BARAD', 'PAVAN ANIL TIDAKE', 'PAVAN DINKAR GALE', 'PAVAN PRAKASHCHANDRA MATWANI', 'PAVAN RAMESH TOPALE', 'PINTYA KISAN BHANDE', 'PRABHAKAR NAGORAO BHOWALE', 'PRADIP PANDURANG SHENDE', 'PRAKASH ALIAS ANTHONY ALIAS THOMAS DHANDAR', 'PRAKASH CHANDRBHAN BENDRE', 'PRAKASH DINESH ATHAVALE', 'PRAKASH JIYALDAS MANWANI', 'PRALHAD DHNYANESHWAR GAYAKWAD', 'PRAMOD DEVRAO BANSOD', 'PRAMOD MAHADEV DHANADE', 'PRAMOD UTTAM DHOKE', 'PRATIK DHANRAJ ZADE', 'PRATIK NAMDEO SHINDE', 'PRAVIN ALIAS PINTYA BHIMYA BANSOD', 'PRAVIN TULSHIRAM KADU', 'PRITAM PANDURANG SURWANSHI', 'PRUTHVI ASHOK WANKHADE', 'RAHAMAT KHAN BISMILLA KHAN', 'RAHUL AMBADAS GETHE', 'RAHUL AMBADAS GETHE', 'RAHUL SUDHAKAR KHOBRAGADE', 'RAJABHAU BOBADE', 'RAJESH BABULAL SOLANKE', 'RAJESH NARAYAN BITAKARI', 'RAJU DATTOPANT ATHAVALE', 'RAJU HOTCHAND ADWANI', 'RAJU SHARAD KALE', 'Rakesh Gopal Gehalod', 'RAMJAN SHAHA TUKDU SHAHA', 'RANU ALIAS RANDEEP CHAINSUKH CHANGANI', 'RASHID KHAN ALIAS MUNGUS GAUSADAR KHAN', 'RAVI ALIAS MAMA LALLUN KHURKHURIYA', 'RAVI CHARAN PATIL', 'RAVI NARAYAN KHADASE', 'RAVINDRA ALIAS GOND SHIVDAS DHOKE', 'RAVINDRA HARIDAS PANEKAR', 'REHANA BANO AHAMAD SHAH', 'Rohit Ganeshrao Ajabe', 'ROSHAN DHASAKAT', 'ROSHAN SANJAY DESHMUKH', 'ROSHAN SURESH KHOBRAGADE', 'ROSHAN VINAYAK ROHANKAR', 'ROSHAN WASUDEV DHASKAT', 'RUPESH BANGADE', 'RUSHIKESH TULSHIRAM KANTALE', 'SACHIN BHASKAR LANJEWAR', 'SACHIN DINKAR CHAUDHARI', 'SACHIN SHRIKRUSHNA DESHMUKH', 'SACHIN WALKHADE', 'SAFDAR BEIG AZAGAR BEIG', 'SAGAR JANARDHAN GOGATE', 'SAGAR JANRAO WANKHADE', 'SAGAR NANAJI WANKHADE', 'SAGAR NARAYAN KHANDARE', 'SAGARSING MAYASING TANK', 'SAIF AHAMAD FARUK AHAMAD', 'SAIYAD ASIF SAIYAD BHURU', 'SAIYAD NIYAJ SAIYAD MUZHAFAR', 'SAIYAD SHAFIQUE SAIYAD RAFIQUE', 'SAIYAD SHAKIR SAIYAD BHURA', 'SALEM DASU GOGALU', 'SALIM KHAN ALIAS SALLU RAFIQUE KHAN', 'SAMAD SHAUKAT SAMAD ABDUL', 'SANDIP DADARAO PAHADAN', 'SANDIP KISAN VAIDYA', 'SANDIP RAMESH RAUT', 'SANDIP SHANKAR KSHIRSAGAR', 'SANGAM HANUMANT MESHRAM', 'SANGITA JADHAV', 'SANJAY ALIAS FANTER DHANSUKH BUDHWANI', 'SANJAY AMBADAS THOSARE', 'SANJAY DEELIP GHODE', 'SANJAY SHANKAR AWARE', 'SANTOSH BANSOD', 'SANTOSH KESHAV KINNAKE', 'SANTOSH SHALIKRAM GAYAKWAD', 'SATISH ALIAS GOLU PURUSHOTTAM SIDAM', 'SATISH ALIAS SATTYA UKADRAO KUROTIYA', 'SATISH BHAGATSINGH SOLANKE', 'SATTYA ALIAS SATISH UKANDRAO KUTORIYA', 'SHAKIR NUR MOHOMMAD KHAN', 'SHAMIULLA KHAN HAFIZULLA KHAN', 'SHAMMI SHAHA MURAD SHAHA', 'SHANKAR SUBHASH BANSOD', 'SHARIK ALI ASHAK ALI KHAN', 'SHASHIKANT PRABHUDAYAL UPADDHYAY', 'SHASHIKUMAR SAHEBRAO TATTE', 'SHEIKH ANSAR NIYAJ ALI', 'SHEIKH ARIF ALIAS GUDDU SHEIKH YUSUF', 'SHEIKH ARIF SHEIKH MUSUD', 'SHEIKH ASIF SHEIKH GUDDU', 'SHEIKH AYUB SHEIKH IBRAHIM', 'SHEIKH CHAND SHEIKH BHURU', 'SHEIKH CHHOTU ARIF SHEIKH DILAWAR', 'SHEIKH CHOTU SHEIKH DILAWAR', 'SHEIKH FIROZ SHEIKH YAKUB', 'SHEIKH GOLU SHEIKH BABA', 'SHEIKH GOLU SHEIKH KADAR', 'SHEIKH HAMID ALIAS MOTU SHEIKH HANIF', 'SHEIKH HAMID ALIAS MOTU SHEIKH HANIF', 'SHEIKH HASAN SHEIKH HUSAIN', 'SHEIKH IRAFAN SHEIKH BISMILLAH', 'SHEIKH JAFAR SHEIKH KARIM', 'SHEIKH JAVED SHEIKH BHURU', 'SHEIKH JAWED ALIAS DADU SHEIKH SABIR', 'SHEIKH JAWED SHEIKH BHURU', 'SHEIKH MATIN SHEIKH MEHABUB', 'SHEIKH RAFIQUE NABIULLA SHEIKH ALIAS SHEKHAR PATIL', 'SHEIKH RIZWAN ALIAS MUNNA MOBILE SHEIKH JALIL', 'SHEIKH SABIR SHEIKH IMAM', 'Sheikh Salman Sheikh Shakur', 'Sheikh Shahid Sheikh Chand', 'SHEIKH TOUFIQUE SHEIKH RAFIQUE', 'SHIVA ALIAS SHIVAJI VITTHAL BHOSALE ALIAS BHOLE', 'SHOBI ALIAS SHOHEB BABBU SARPANCH', 'SHRIKRUSHANA PINTYA DEVIDAS GAHUKAR', 'SHUBHAM GAJANAN SAYANKE', 'SHYAM GAJANAN PURI', 'SHYAM MADAN PATHAK', 'SINNA CHINNA ATAPALLI', 'SONYA ALIAS MANGESH BHIMRAO CHANDURKAR', 'SUBODH BHIMARAO DHAKADE', 'SUDHIR DADARAO PUND', 'SUDHIR LAXMAN JAVANJAL', 'SUDHIR SURESH LAHUPANCHANG', 'SUHAS ALIAS PRAKASH ASHOK JOSHI', 'SUNIL JAYDEV MESHRAM', 'SUNIL PRAKASH GULSUNDARE', 'SUNIL SHANKARRAO MATE', 'SUNIL SHYAMRAO UKE', 'SUNNY SUNIL BIJAVE', 'SURAJ GAJANAN DESHKAR', 'SURAJ PURUSHOTTAM GUPTA', 'SURENDRA RAOSAHEB KORE', 'SURENDRA UDHAVRAO WAKODE', 'SURESH PRAKASH RANGARI', 'SURESH SUDHAKAR GANDHE', 'SUSHANT ARUN GANJARE', 'SUSHIL ALIAS KHANDYA WANKHADE', 'SUYASH CHANDRASHEKHAR DORLE', 'SWAPNIL MOTIRAM MESHRAM', 'Swapnil Vinay Bangre', 'TAANYA ALIAS TANAJI VITTHAL BHOSALE', 'TIRUMALLI WALKISAN ATAPALLI', 'UJWAL ALIAS SONU SHEKHAR KAMKARE', 'UMESH BHUJANGRAO MAHALLE', 'VASIM KHAN YUSUF KHAN', 'VIJAY NAJUK INGALE', 'Vijay Pandurang Raybole', 'VIJAY SANJAY SURYAWANSHI', 'VIJAY TULASHIRAM KALE', 'VIKAS RAMJI CHAPALKAR', 'VIKKY ALIAS ASHOK GANOSKAR', 'VIKKY DHANARAJ KHANDARE', 'VIKKY RAJENDRA GADLING', 'VINOD ARUN KOTHE', 'VIRANNA BANKKATAPPA ZIRPILALU', 'VISHAL ARUN PAWAR', 'VITTHAL SHANKARAO MANKAR', 'Vivek Alias Bikku Ravindra Pande', 'VIVEK ALIAS BODYA VINAYAK NIRMAL', 'WAHID KHAN SAID KHAN', 'WAMAN JAGAN NAIK', 'WASANT SHANKAR CHAUDHARI', 'YOGESH ALIAS LAKHAN RAMESH WANKHADE', 'YOGESH GOVIND TAYADE', 'YUSUF ALI ASHAF ALI KHAN', 'ZAHIR SHEKHU KHURSHID ABBAS', 'ZAKIR HUSAIN JINNATALI', 'RAJESH KUMAR', 'Shri Deepankar Barman', 'Shr Hasen Ali', 'Shri Mohibul Prodhani', 'Azirul Islam alias Aziul Hoque', 'Shri Sunil Gogoi', 'Shahabaj Jakaria Shikdar', 'Ferdynald Kharkamni', 'Shri Arun Kumar Jain', 'Shri Santanu Mizar', 'Shri Amit Paul', 'Shri Lakstar Khariap', 'Shri Pujam Gurung', 'Shri Tilok Dorjee', 'Shri Mukhiya Singh', 'Shri Jhuggo Jasoda', 'Shri Shanborlang Rani alias Dengdeng', 'Shri Rohit', 'Bringo Lyngdoh', 'Nayan Bhattacharjee', 'Shri Sandeep Sunar', 'Shri Din Dayal Sharma', 'Shri Harlal Jat', 'Shri Majidul Khan', 'Shri Dilip Baspor', 'Shri Eyahia Ahmed', 'Shri Biswajit Yadav', 'Shri Amit Ghosh', 'Shri Mithun Sharma', 'Shri Nihar Ranjan Bhattachariya ', 'Shri Santosh Hajong ', 'Smti Balarisa Nengnong', 'Shri Diganta Kumar Adhikari', 'Shri Dilip Kumar', 'Shri Arjun Burman', 'SHRI DANIEL HAWK ', 'Shri Ramesh Gurung ', 'Smti Anandi Chapagai', 'Shri Khimananda Chapagai', 'Biswng Prasad Chattri', 'Shri Tapan Ojha', 'Shri Manseng D Sangma', 'Shri Lalit Dey', 'Shri Nur Mohmmed', 'Shri Asraful Ali', 'Shri Babeshor Kalandi', 'Shri Rex Briller R Marak', 'Miss Eunice Zimik', 'Shri Prema', 'Shri Shynsharlang Thongni', 'Shri Sumon Namo ', 'Smti Jesica Kharkongor ', 'Shri Mukesh Sangma', 'Bhim Singh', 'Shri Konesshon Rodborn ', 'Shri Thoudam Prasanta Singh  ', 'Chatu', 'Madhurendra Singh', 'Rousan', 'Bablu Rewani', 'Sunil Madni', 'Tribeni Prasad', 'Guljar Ansari', 'Samim', 'Kishore Mondal', 'Sakir Ansari', 'MD. SIRAJ', 'MD. NAUSHAD KHAN', 'MD. AKTAR KHAN', 'AKBAR KHAN', 'PABAN KUMAR YADAV', 'AMIT KUMAR YADAV', 'KALIYA KURMI', 'PINTU DEY', 'DHARMENDRA', 'UJJAL BOURI', 'MD NAWSAD', 'CASHIER', 'SK. LAL', 'RAKESH HELA', 'RAJESH VERMA', 'NANDA BOURI', 'KRISHNA DAS', 'KARA RAJ BANGSI', 'KRISHNA YADAV', 'BAIJU PRASAD RAM', 'LOKE NATH MUKHERJEE', 'SUBRATA SARKAR', 'PRITAM DAS', 'RANJIT HELA', 'RAJU RUIDAS', 'RAJU BOURI', 'RAHUL YADAV', 'PINTU RUIDAS', 'LAXMAN LAMA', 'LACHMI SAHANI', 'KARKAT DAS', 'JOGI DAS', 'GOUR SENGUPTA', 'BHALTU PASI', 'BESAN RUIDAS', 'BALDEV TURI', 'AUSTA RUIDAS', 'ANAND PASWAN', 'TIPU ANSARI', 'SUSHIL RAM', 'SURAJIT SARKAR', 'SK TAHIR', 'SK  SAMSOL', 'SK MOHIBUL', 'SK KHALID', 'SK IMAMUL', 'SK ILIAS', 'SK ASHRAF', 'SK AKHTAR', 'SK ABAR ALI', 'SARUDDIN', 'PRADIP KR TIWARI', 'MRINAL KANTI GHOSH', 'MOHAN RUIDAS', 'MD SHANAWAR', 'MD RIZWAN', 'MD NOUSAD', 'MD-IMTIYAJ', 'MANOJ-DOM', 'UTPAL-GHOSH', 'JITEN-PAUL', 'BADYANATH MONDAL', 'BURO BOURI', 'BIRJU PASWAN', 'SANJOY KR SUKLA', 'Mithilesh Kumar Singh', 'Khusbu', 'Rajesh Paswan', 'Manoj Mallick', 'Amar Mahato', 'MOHAN', 'Kanahi Bouri', 'Nimai Ruidas', 'Sanjoy Ruidas', 'Santosh Rewani', 'Sushil', 'Srimanta Ruidas', 'Manik Das', 'Rahul', 'RAJU', 'Gour', 'Raju Bauri', 'Besan', 'Bhaltu', 'Kartak Das', 'Jogi', 'Lachmi', 'Anand Paswan', 'Austa', 'Astik', 'BALDV TURI', 'LAXMAN']